SU-SWS/ood-giving-campaign

src/hooks/useStoryblokState.ts, src/pages/index.tsx, src/pages/{storyblokEntry.full_slug}.tsx
- Use temporary solution (link in code comment) to override useStoryblokState from gatsby-source-storyblok
- Allow for refreshing content after clicking Save or publish in visual editor.
1. Please review retro - this is a temporary workaround and is easily reversible.
=> Use custom useStoryblokStory hook which force refresh content after saving/publishing

gatsby-config.ts, gatsby-node.ts, src/components/Container/Container.styles.ts, src/components/Container/Container.tsx, src/components/Container/index.ts, src/components/FlexBox/FlexBox.styles.ts, src/components/FlexBox/FlexBox.tsx, src/components/FlexBox/FlexBox.types.ts, src/components/FlexBox/index.ts, src/components/GlobalFooter/GlobalFooter.styles.ts, src/components/GlobalFooter/GlobalFooter.tsx, src/components/GlobalFooter/index.ts, src/components/Layout.tsx, src/components/StanfordLogo/StanfordLogo.styles.ts, src/components/StanfordLogo/StanfordLogo.tsx, src/components/StanfordLogo/index.ts, src/components/Typography/SrOnlyText.tsx
- Add GlobalFooter and other Layout/Identity components
- Add GlobalFooter to Layout component as a Gatsby Slice
- make Global Footer sticky to bottom
- Retro
1. Look at the preview and see that the Global Footer is showing up
2. Look at code and comments below
- JIRA ticket(s) - GIVCAMP-58, GIVCAMP-33
=> GIVCAMP-58 GIVCAMP-33 | More components; Gatsby Slice Global Footer

src/components/Container/Container.tsx, src/components/Grid/Grid.tsx, src/components/Grid/WidthBox.styles.ts, src/components/Grid/WidthBox.tsx, src/components/VerticalCard/VerticalCard.tsx, src/utilities/config.ts, src/utilities/getProcessedImage.ts, src/utilities/getSbImageSize.ts
- New image utilities that uses the new version of Storyblok Image Service (different from the one we use in SAA Homesite )
- Add WidthBox which we'll need later for x of 12 column type of width options
- Retro
1. Look at preview and inspect the card image with the pallas cat
2. See that it uses the new format of the Storyblok image service, and that it uses our masked URL from the assets CDN
Note: image focus is supported and supported image types are converted to webp format for supported browsers
Note: it should preserve the animated GIFS (the pusheen) - it wouldn't get turned into a webp
- JIRA ticket(s) - GIVCAMP-71
=> GIVCAMP-71 | Add updated Storyblok image service processing with masked CDN URL

src/components/Cta/CtaLink.tsx, src/components/Logo/Logo.tsx, src/hooks/useAddUtmParams.ts, src/hooks/useFilteredUtmParams.ts, src/pages/index.tsx
- Updated CtaLink to absorb more functionality of SbLink from Homesite with updated code
- Add hooks to get specified list of UTM params and to add those params to a URL
- Retro
1. Go to https://deploy-preview-30--giving-campaign.netlify.app/?utm_medium=instagram&utm_monkey=chimp&utm_campaign=giving
2. Click on the Logo, or go to the Light Section and click on the first card
3. Check that only utm_medium and utm_campaign have been preserved. utm_monkey is gone
4. Inspect the link in the 2nd card in the Dark section
5. Check that it has the rel, title, data-test added to the a tag.
- JIRA ticket(s) - GIVCAMP-69
=> GIVCAMP-69 | updated Storyblok Link field support + keep filtered list of UTM params

gatsby-browser.ts, gatsby-browser.tsx, src/components/Hero/HomepageHero.tsx, src/components/NumberCounter.tsx, src/components/Parallax/Parallax.tsx, src/pages/index.tsx, tsconfig.json
- Reduce bundle size of Framer Motion following documentation
https://www.framer.com/motion/guide-reduce-bundle-size/
- Retro
1. Go to the preview and check that the previous animations are still all working.
2. Look at code
- JIRA ticket(s) - GIVCAMP-68
=> GIVCAMP-68 | Reduce bundle size of Framer Motion

src/components/Hero/HomepageHero.tsx, src/components/Storyblok/SbSection.tsx
- Occasionally, when you resized the browser, a line could appear under the video
- This appears to be a browser rendering issue.
- Retro
1. Resize the browser and check that you don't see a white line anymore.
2. Look at approach (there are multiple ways)
- JIRA ticket(s) - GIVCAMP-86
=> GIVCAMP-86 | Add fix for a line that appears sometimes when browser is resized

src/components/Animate/AnimateInView.tsx, src/components/Animate/AnimationMap.ts, src/components/Animate/index.ts, src/components/Grid/Grid.tsx, src/components/Hero/HomepageHero.tsx, src/components/Logo/Logo.styles.ts, src/components/SplitPoster/PosterContent.tsx, src/components/Storyblok/SbVerticalCard.tsx, src/components/Typography/Text.tsx, src/components/VerticalCard/VerticalCard.tsx
- Add AnimateInView wrapper component - can take input from Storyblok and let user pick animation type and delay (more later)
- Restructure the homepage hero so it's more flexible, plus can animate the fade in for the background gradient first
- Vertical cards - render CTA if there's a cta label provided, otherwise add the link inside the heading.
- Retro
1. Look at the preview and the code
2. Note: on Storyblok, I added delays to the cards to stagger the animation effect.
- JIRA ticket(s) - GIVCAMP-78
=> GIVCAMP-78 | In View Animation wrapper; redo homepage hero animation and structure; vertical card updates

gatsby-node.ts, src/components/Cta/CtaLink.tsx, src/pages/{storyblokEntry.full_slug}.tsx
- Storyblok link fix - for cachedUrl - need to add "/" in front
- Do not pass utm params to external links
- Retro
1. Go to the preview and scroll down to the split poster
2. Click on the CTA link button
3. Verify that it scrolls to the page top of the /about-test page
4. On the /about-test page, scroll down to the bottom
5. Click on the red button and verify that it takes you back to home, not /about-test/home
- Other PRs
=> Nojira | Add missing internal link logic to add / in front of cached URL

src/components/Grid/GridAlternating.tsx, src/components/Layout.tsx, src/components/Storyblok/SbGridAlternating.tsx, src/components/Storyblok/SbSection.tsx, src/components/Storyblok/SbThemeCard.tsx, src/components/Storyblok/SbVerticalCard.tsx, src/components/Storyblok/SbWysiwyg.tsx, src/components/VerticalCard/ThemeCard.tsx, src/components/VerticalCard/VerticalCard.styles.tsx, src/components/VerticalCard/VerticalCard.tsx, src/components/VerticalCard/index.ts
- Create Theme Cards out of Vertical Cards
- Styles clean up
- Add auto select text color based on parent section background color
- Add superhead field for Storyblok Sections
- Retro
1. Look at the preview and scroll down to see the theme cards
2. Look at code and things called out
- JIRA ticket(s) - GIVCAMP-104
=> GIVCAMP-104 | Create theme cards; add section superhead

package-lock.json, package.json
- Update Gatsby to 5.9.0
- Update Gatsby related plugins to latest version
- Note: due to us using the override as a workaround for gatsby-source-storyblok's incompatibility for Gatsby v5, for this PR, we remove the override in package.json, uninstalled gatsby and related plugins, add the override to gatsby 5.9.0, and reinstall all the things we removed.
- Retro
1. Look at the preview and make sure it works the same as before
2. Look at the list of things that were updated
=> Nojira | Update gatsby to 5.9.0 and all gatsby related plugins to latest

src/components/Bracket/Bracket.styles.ts, src/components/Bracket/Bracket.tsx, src/components/Bracket/BracketCurve.tsx
- I previously create the top left corner of the bracket, then use CSS transform to get the other 3 corners of the bracket curved and then the "close" version (flipping the "open" one) of the bracket, but found that it introduces visual imperfections.
- Fix it by not using transform
- Retro
1. Go to preview and scroll to bracket cards, look at the ones with the close bracket particularly, resize the cards (LG and up) and make sure that the bracket corners look good
Before (bad)
After (should be smooth)
- JIRA ticket(s) - GIVCAMP-108
=> Nojira | Fix visual artifacts with brackets due to CSS transform

src/components/Storyblok/SbBracketCard.tsx, src/components/Storyblok/SbThemeCard.tsx, src/components/Storyblok/SbVerticalCard.tsx, src/pages/index.tsx, src/utilities/colorPalettePlugin.ts
- Support for new Storyblok plugin custom color picker for bracket card, vertical card, theme card tab colors
- Retro
1. Look at the preview and see that all the card tab colors are still there. The tab color field has been replaced with the new Storyblok palette plugin instead of datasource on the backend.
=> Nojira | Set up SB components to use new Storyblok custom palette picker

gatsby-ssr.tsx, src/components/Container/Container.styles.ts, src/components/Cta/Cta.styles.ts, src/components/Logo/Logo.styles.ts, src/components/RichText.tsx, src/components/StanfordLogo/StanfordLogo.styles.ts, src/components/Typography/typography.styles.ts, src/components/VerticalCard/VerticalCard.styles.tsx, src/tailwind/plugins/base/gc-base.js, src/utilities/datasource.ts
- Inline links should be digital red (regular) and digital red dark on hocus (can see in WYSIWYG)
- Use SAA Black for text color instead of decanter black everywhere that it's used
- Retro
1. Go to the preview
https://deploy-preview-58--giving-campaign.netlify.app/
https://deploy-preview-58--giving-campaign.netlify.app/about-test/ (WYSIWYG on this page - light and dark mode)
3. Check that everywhere you see black text (section heading, card heading, body, WYSIWYG etc, it uses the SAA black color (#181D1C)
4. See that the light mode WYSIWYG, and that the link color is digital red, hocus to digital red dark.
- JIRA ticket(s) - GIVCAMP-111
=> GIVCAMP-111 | Text and link color updates

src/components/Cta/Cta.styles.ts, src/components/HeroIcon/HeroIcon.styles.tsx, src/components/HeroIcon/HeroIcon.tsx, src/components/Temporary/DemoContent.tsx, src/components/VerticalCard/VerticalCard.tsx
- Replace original triangle icon with rounder icon (trying PlayIcon from HeroIcons) and addd "triangle-up" option
- Update CTA padding
- Retro
1. Look at the preview
2. See that the CTAs with the solid triangles are now slightly rounder; check that they all look good
Note: We're getting rid of all the all caps buttons so no need to worry about positioning of icons for those uppercase buttons.
- JIRA ticket(s) - GIVCAMP-112
=> GIVCAMP-112 | Triangle icon update; minor CTA update

src/components/Bracket/Bracket.styles.ts, src/components/Hero/HomepageHero.tsx, src/components/HeroIcon/HeroIcon.styles.tsx, src/components/Intro/Intro.tsx
- This PR originally was meant to update the animation behavior of the hero. I only include the play/pause button updates because I think the on scroll change isn't good for usability. I'll put that work into a different PR so we can merge this in.
- Use the outline version of the bracket in intro, since the solid one combined with the animation creates visual artifacts that can't seem to go away
1. Look at the hero play button inside the bracket as you scroll down, and the background video play pause at the left right corner of the hero
- JIRA ticket(s) - GIVCAMP-122
=> GIVCAMP-122 | Update play pause buttons in Hero; change intro bracket to outline

src/components/Bracket/Bracket.styles.ts, src/components/Bracket/Bracket.tsx, src/components/Bracket/BracketCurve.tsx, src/components/BracketCard/BracketCard.styles.ts, src/components/BracketCard/BracketCard.tsx, src/components/Container/Container.tsx, src/components/Cta/CtaContent.tsx, src/components/Cta/getCtaClasses.ts, src/components/FlexBox/FlexBox.tsx, src/components/GlobalFooter/GlobalFooter.tsx, src/components/Grid/Grid.tsx, src/components/Grid/GridAlternating.tsx, src/components/HeroIcon/HeroIcon.tsx, src/components/ImageOverlay.tsx, src/components/Logo/Logo.styles.ts, src/components/Logo/Logo.tsx, src/components/Masthead/Masthead.tsx, src/components/RichText.tsx, src/components/SkipLink.tsx, src/components/SplitPoster/PosterContent.tsx, src/components/SplitPoster/SplitPoster.styles.tsx, src/components/StanfordLogo/StanfordLogo.tsx, src/components/Temporary/ThemeSection.tsx, src/components/Typography/Paragraph.tsx, src/components/Typography/Text.tsx, src/components/VerticalCard/VerticalCard.tsx, src/components/WidthBox/WidthBox.tsx
- Replace dcnb with cnb because we don't need the dedupe the way we're using it
- Author says dedupe version is much slower. Looking at the benchmark, we don't get much advantage using it over classname package if we use the dcnb version
https://github.com/xobotyi/cnbuilder/tree/master/benchmark
- Retro
1. Look at the preview and see that things still look the same
- JIRA ticket(s) - GIVCAMP-131
=> GIVCAMP-131 | Replace dcnb with cnb for speed

src/components/Homepage/ThemeSection.tsx, src/components/Storyblok/SbSection.tsx
- Update color bar in section to extend to superhead
- Retro
1. Look at preview and the /about-test page
2. Check that sections with color bar now extends upward to include the superhead (if there is a superhead)
- JIRA ticket(s) - GIVCAMP-129
=> GIVCAMP-129 | Update color bar in section to extend to superhead

gatsby-config.ts, src/components/BracketCard/BracketCard.styles.ts, src/components/Cta/Cta.styles.ts, src/components/Cta/CtaGatsbyLink.tsx, src/components/Grid/Grid.styles.ts, src/components/Layout.tsx, src/components/Storyblok/SbGrid.tsx, src/components/Storyblok/SbStoryCard.tsx, src/components/Storyblok/SbThemeCard.tsx, src/components/Temporary/DemoContent.tsx, src/components/VerticalCard/StoryCard.tsx, src/components/VerticalCard/ThemeCard.tsx, src/components/VerticalCard/VerticalCard.styles.tsx, src/components/VerticalCard/VerticalCard.tsx, src/components/VerticalCard/index.ts, src/pages/index.tsx, src/pages/{storyblokEntry.full_slug}.tsx, src/utilities/resolveRelations.ts, src/utilities/routes.ts, src/utilities/slugify.ts
- Story cards that supports story picking (referencing published story) and manual field entering (card title, image, link)
- Strategy for resolving Storyblok relations using the new method
- Story card style updates
- Grid gap options added
- Retro
1. Go to https://deploy-preview-81--giving-campaign.netlify.app/about-test/ and look at the story card section
2. The 1st 3 cards are currently referencing Storyblok published stories. The 4th one with the handsome cat is the manual one (no manual taxonomy at the moment), also, heading is set to use the larger font size
3. Scroll further down to see light mode
- JIRA ticket(s) - GIVCAMP-127, GIVCAMP-130
=> GIVCAMP-127, GIVCAMP-130 | Story card and theme card updates; Storyblok resolve story relations (new method)

src/components/Cta/Cta.styles.ts, src/components/ImageOverlay.tsx, src/components/SplitPoster/SplitPoster.tsx, src/components/Temporary/DemoContent.tsx
- Add option to have 2 curves on opposite corners for CTAs (options added in Storyblok also), ie, top left + bottom right, or top right + botton left (in addition to the current options to have 1 curved corner or no curved corners at all)
- Play with the idea to add a variant of white ghost button with a translucent black overlay. This helps with text contrast over images, eg, in the split posters.
- Fix flex alignment when there are multiple CTAS so they don't stretch to the same width
- Retro
1. Go to 
https://deploy-preview-83--giving-campaign.netlify.app/about-test/
2. Scroll down to see the 1st split poster with a button with 2 curves
2. Look at the split poster with ghost button over images, see the variant with black overlay
4. Scroll further down to see the demo CTA sections, eg, …
=> GIVCAMP-134 | Allow double curved CTAs and add white ghost with dark overlay variant; split poster CTA group align fixup

src/components/Cta/Cta.styles.ts, src/components/Homepage/FindPurposeSection.tsx, src/components/Homepage/HomepageHero.tsx, src/components/Homepage/Intro.tsx, src/components/Homepage/ProgressSection.tsx, src/components/Homepage/ThemeSection.tsx, src/components/Logo/Logo.styles.ts, src/components/Logo/Logo.tsx, src/components/Logo/LogoHorizontal.tsx, src/components/Masthead/Masthead.tsx, src/components/Storyblok/SbLogo.tsx, src/tailwind/plugins/base/gc-base.js
- Masthead POC (clients want to see this behavior as recommended by Kerri, kind of a meet in the middle solution for a sticky masthead)
- At the top of the page, the background color of the masthead is transparent, logo and buttons are white
- As one scrolls down, the masthead goes away
- When one scrolls back up, the masthead reappear and stay sticky at the top. However, this version has a solid white background with black logo and buttons.
- Some misc tweaks here and there
- Retro
1. Go to the preview
2. Look at the masthead at the top (without scrolling)
3. Scroll down and see that the masthead goes away
4. Scroll further down, then scroll back up to see the white solid version of the masthead reappears as sticky at the top
- JIRA ticket(s) - GIVCAMP-117
=> GIVCAMP-117 | Masthead that becomes visible when scrolling up

src/components/Cta/Cta.styles.ts, src/components/Masthead/Masthead.tsx
- Firefox's long time bug when combining transform and curved radius
https://stackoverflow.com/questions/71123245/firefox-scaling-issues-causes-pixelated-blurry-borders
- This PR should fix it
- Retro
1. Use Firefox
2. Scroll down and then up to see the white background version of the masthead
3. The button should be ok now
Before:
After (now):
- JIRA ticket(s) - GIVCAMP-117
=> GIVCAMP-117 | Masthead CTA Firefox rendering bug fix

src/components/PageHead/SEO.tsx, src/pages/index.tsx, src/pages/{storyblokEntry.full_slug}.tsx
- This is only for metatag in the HTML head - adding support for noindex (boolean) and Canonical URL (Storyblok link field if it's entered, or self-referencing if this is left empty in Storyblok)
- Retro
1. Go to the homepage
https://deploy-preview-86--giving-campaign.netlify.app
`No Canonical URL is entered on Storyblok; noindex is false.`
Look at the page HTML head, and check that the canonical URL is set to the above URL (self-referencing canonical URL)
2. Go to the about-test page:
https://deploy-preview-86--giving-campaign.netlify.app/about-test/
` noindex is true`
Check that you see the noindex metatag
3. Go to this story "The future grows on a farm"
https://deploy-preview-86--giving-campaign.netlify.app/stories/the-future-grows-on-a-farm/
`Canonical URL is entered as …
=> GIVCAMP-140 | Canonical URL and noindex in page metatags

src/components/Banner/Banner.styles.ts, src/components/Banner/Banner.tsx, src/components/Banner/index.ts, src/components/Cta/Cta.styles.ts, src/components/Layout.tsx, src/components/LocalFooter/LocalFooter.tsx, src/components/Storyblok/SbBanner.tsx, src/pages/index.tsx, src/pages/{storyblokEntry.full_slug}.tsx, src/utilities/datasource.ts
- Getting the Banner component connected with Storyblok; add dark mode and clean up props
- Responsive behavior of Banner
- Temporary placements of textured bars on the site (below the hero, above the local footer, and above the ankle if there is an ankle). Will revisit after we create a "bar" component in Storyblok.
- Finalize white ghost button with dark overlay version
- Retro
1. Go to https://deploy-preview-87--giving-campaign.netlify.app/ and scroll to right above the local footer
2. Look at the Banner (light version) with larger headline
3. See if responsive behavior seem legit
4. Go to https://deploy-preview-87--giving-campaign.netlify.app/about-test/ and scroll to above the local footer
5. See the Banner (dark version) with the smaller headline
6. Again check responsive
- JIRA …
=> GIVCAMP-92 | Storyblok Banner component

src/components/Cta/Cta.styles.ts, src/components/Masthead/Masthead.tsx
- Masthead - on scrolling up, use dark color schedule (black bg with white logo and buttons), with reduced vertical offset between the 2 buttons (which shrinks the height of the masthead)
- Other minor fixups
- Responsive and spacing finetune will be dealt with later after design is finalized
- Approved by clients
1. Go to the preview and scroll down
2. Scroll back up to see the masthead reappearing like this
- JIRA ticket(s) - GIVCAMP-148
=> GIVCAMP-148 | Explore dark theme masthead + reduce button offset when scrolling up

src/components/Grid/Grid.styles.ts, src/components/Storyblok/SbGrid.tsx
- Adding grid column and extra grid gap options to the Storyblok Grid
- Retro
1. Go to the Initiative page https://deploy-preview-91--giving-campaign.netlify.app/initiatives/
2. Look at the card grid
3. It should have a grid gap of 4px (both horizontal and vertical)
4. on LG+, there should be 4 columns
5. SM-MD = 2 columns
6. XS = 1 column
- JIRA ticket(s) - GIVCAMP-154
=> GIVCAMP-154 | Add Storyblok Grid options

components/Cta/Cta.styles.ts, components/HeroIcon/HeroIcon.styles.tsx, components/Masthead/Masthead.tsx
- Put in the real CTA responsive now that they're in
- Don't scale down the masthead CTAs on scrolling up on mobile (only do that for desktop)
- Retro
2. At mobile breakpoint, scroll down, then scroll back up - check that the menu buttons should not change size (when the solid black background masthead reappears on scrolling up)
- JIRA ticket(s) - GIVCAMP-149
=> GIVCAMP-149 | Responsive CTAs

components/Cta/Cta.styles.ts, components/Logo/Logo.styles.ts, components/Logo/LogoLockup.tsx, components/Logo/index.ts, components/Masthead/Masthead.tsx, components/StoryPoC/VideoScrollStory.tsx
- Use the Giving lockup for the logo in the masthead, and remove the menu button with style updates.
- Add responsive behavior
- Retro
1. Go to these 2 pages and see both the light and dark version of the masthead, also, scroll down for a while, then back up to see the compact version of the masthead. Check mobile behavior also.
https://deploy-preview-116--giving-campaign.netlify.app/stories/poc-video-scrolling-story
https://deploy-preview-116--giving-campaign.netlify.app/stories/harnessing-satellite-imagery-ai-to-help-fight-poverty
- JIRA ticket(s) - GIVCAMP-189
=> GIVCAMP-189 | Masthead changes and add lockup

next.config.js
- Modularize import for HeroIcons to prevent compilation of hundreds the unused icons (HeroIcons use a barrel file)
- See https://nextjs.org/docs/architecture/nextjs-compiler#modularize-imports
- And this discusssion https://github.com/vercel/next.js/issues/48748
- Note: After I looked at it for a while, it looks like next.js made this a default for heroicons - the code is currently in canary and not in the next.js version we're using v13.4.9 (I would like to stay at this version for now). We might be able to remove this in the future, but for now it is good to have. (And it was good for me to look into this)
https://github.com/vercel/next.js/pull/53902
- Whenever
1. Look at the preview and see that the arrow icons are still appearing
2. Look at code, and the links in the summary of this …
=> GIVCAMP-176 | Modularize import for heroicons

components/BlurryPoster/BlurryPoster.styles.tsx, components/BlurryPoster/BlurryPoster.tsx, components/BlurryPoster/index.ts, components/Homepage/HomepageSplitHero.tsx, components/Homepage/IdealFellow.tsx, components/RichText.tsx, components/Storyblok/SbBlurryPoster.tsx, components/Storyblok/SbGrid.tsx, components/Storyblok/SbHomepage.tsx, components/Storyblok/SbHomepageMvp.tsx, components/StoryblokProvider.tsx, components/Typography/typography.styles.ts, package-lock.json, package.json, tailwind/plugins/components/gc-typography.js
- New SbHomepageMvp component (keeping the old SbHomepage, but rebuild the "home" page to use the MVP storyblok component
- New BlurryPoster component
- eslint update
- remove netlify nextjs plugin so it's always using the latest during build
- Retro
1. GO to the preview and look at the homepage. Scroll down and you'll see the blurry background posters.
https://deploy-preview-123--giving-campaign.netlify.app/ (SbHomepageMvp component)
2. https://deploy-preview-123--giving-campaign.netlify.app/home-old
And see that the old version of the homepage is there (SbHomepage component)
- JIRA ticket(s) - GIVCAMP-201
=> GIVCAMP-201 | Blurry background poster; SbHomepageMvp component; remove netlify nextjs plugin

components/BlurryPoster/BlurryPoster.styles.tsx, components/BlurryPoster/BlurryPoster.tsx, components/Homepage/HomepageSplitHero.tsx, components/Storyblok/SbBlurryPoster.tsx, components/Storyblok/SbSection.tsx, tailwind.config.ts, tailwind/plugins/components/layout.js
- Options and responsive behavior for Blurry Poster
- Retro
1. Look at the homepage and see the 2 blurry posters
https://deploy-preview-124--giving-campaign.netlify.app/
2. Check responsive behavior
- JIRA ticket(s) - GIVCAMP-201
=> GIVCAMP-201 | Blurry poster options and responsive

components/BlurryPoster/BlurryPoster.styles.tsx, components/BlurryPoster/BlurryPoster.tsx, components/Storyblok/SbBlurryPoster.tsx, components/Storyblok/Storyblok.types.ts
- Add a way for the content author to add mixed typography into the Blurry Poster headline (mixed serif and Druk fonts)
- Retro
1. Look at the preview and scroll to the 2 blurry posters and see the animation when they're in view
https://deploy-preview-125--giving-campaign.netlify.app/
2. Check that the mixed typography works for all breakpoints, and for both regular heading size, and for small heading size (small heading only for certain breakpoints, on mobile and largest desktop resolution, they have the same font size)
- JIRA ticket(s) - GIVCAMP-205
=> GIVCAMP-205 | Allow for mixed typography for blurry poster and add animation

components/BlurryPoster/BlurryPoster.styles.tsx, components/ImageOverlay.tsx, components/Storyblok/SbSection.tsx, components/VerticalCard/VerticalCard.tsx
- Section background image option with light and dark overlay
- Option to add subhead
- Option for small heading size
- style updates
- Hide taxonomy tags for Story Cards for MVP
- REtro
1. https://deploy-preview-126--giving-campaign.netlify.app
2. Look at the different story card sections
- JIRA ticket(s) - GIVCAMP-200, GIVCAMP-219
=> GIVCAMP-200, GIVCAMP-219 | Section background image and other new options

.eslintrc.json, components/BracketCard/BracketCard.styles.ts, components/Grid/Grid.styles.ts, components/Grid/Grid.tsx, components/ImageOverlay.tsx, components/Storyblok/SbGrid.tsx, components/Storyblok/SbSection.tsx, components/Storyblok/SbWysiwyg.tsx, components/VerticalCard/VerticalCard.styles.tsx, components/VerticalCard/VerticalCard.tsx, components/WidthBox/WidthBox.styles.ts, components/WidthBox/WidthBox.tsx
- Option to right align Section header
- Add options for grid 
- Create layout for Story Cards on the homepage
- Retro
1. go to https://deploy-preview-128--giving-campaign.netlify.app/
2. Look at the 1, 2, 3, 4 up story card sections
3. Look at the different breakpoints
- JIRA ticket(s) - GIVCAMP-220
=> GIVCAMP-220 | Grid options and story card section layouts

components/BlurryPoster/BlurryPoster.styles.tsx, components/BlurryPoster/BlurryPoster.tsx, components/Storyblok/SbBlurryPoster.tsx
- Add dark overlay for blurry poster (mandatory for mobile, optional Storyblok toggle for desktop)
- Minor fixups
- Retro
1. Go to the preview and look at the blurry posters on mobile, check that they both have a dark overlay
Before:
This PR:
2. Look at this poster on desktop breakpoint, check that it has a dark overlay
Before:
This PR:
- JIRA ticket(s) - GIVCAMP-233
=> GIVCAMP-233 | Add dark overlay for blurry poster; minor updates

components/Storyblok/SbSection.tsx
- Fixup for Sections with no bar color options selected
- Retro
1. Go to the preview and look at all the Sections now with no color bars selected and check that they're align to the edge of the centered container (left or right side depending on whether the section header is left or right aligned)
=> Fix | Margin fix when no bar color is selected for Sections

components/BlurryPoster/BlurryPoster.styles.tsx, components/BlurryPoster/BlurryPoster.tsx, components/Storyblok/SbBlurryPoster.tsx, components/Storyblok/SbHomepageMvp.tsx
- Add superhead for blurry poster
- Add dark overlay for mobile poster for a11y whether dark overlay is turn on or off
Note: client has already approved of the look of the superhead
- Retro
1. Go to the homepage
https://deploy-preview-137--giving-campaign.netlify.app/
2. Look at the superhead on both variants (image on left or right) of the blurry posters and check all the responsive.
3. Check that for this poster, it has a dark overlay in the background on mobile (XS-MD)
- JIRA ticket(s) - GIVCAMP-235
=> GIVCAMP-235 | Add superhead for blurry poster; dark overlay for mobile

components/Sidebar/SidebarCard.styles.ts, components/Storyblok/SbStoryMvp/SbAboveContent.tsx
- Change layout of the sidebar/intro story area from XL to infinity
- NOTE: Kerri and Ali have approved this
- Retro
1. Go to a story
https://deploy-preview-136--giving-campaign.netlify.app/stories/test-story-hero-mixed-font-horizontal
2. Look at the sidebar/intro area
New (this PR)
Old
- JIRA ticket(s) - GIVCAMP-234
=> GIVCAMP-234 | Alt layout idea for above content section in stories

components/BlurryPoster/BlurryPoster.styles.tsx, components/BlurryPoster/BlurryPoster.tsx, components/Hero/StoryHeroMvp.tsx, components/Storyblok/SbStoryMvp/SbStoryMvp.tsx
- Add an optional superhead field for Story heroes
- Retro
1. Go to stories like
https://deploy-preview-146--giving-campaign.netlify.app/stories/the-most-wicked-problems
https://deploy-preview-146--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose
and verify that you can see the superhead above the large story title
2. Check that responsive looks good
- JIRA ticket(s) - GIVCAMP-243
=> GIVCAMP-243 | Add support for superhead field in Story Heroes (MVP)

netlify.toml, plugins/netlify-plugin-contextual-auth/index.js, plugins/netlify-plugin-contextual-auth/manifest.yml
- Adds (browser based) basic auth to all contexts
- Whenever
- 🤷 
1. Navigate to the [build preview](deploy-preview-144--giving-campaign.netlify.app)
2. Do not enter anything for username
3. Enter `0nPurrpose` for password
=> GIVCAMP-192: Add basic auth plugin

components/FeaturedStories/FeatureMasonry.tsx, components/Hero/StoryHeroMvp.tsx, components/Storyblok/SbStoryMvp/SbStoryMvp.tsx, components/Storyblok/SbTexturedBar.tsx, components/StoryblokProvider.tsx, components/TexturedBar/TexturedBar.tsx, components/TexturedBar/index.ts
- Create a Textured Bar component in Storyblok where the content author can pick from images in a specific folder in Storyblok.
- It should be available below story hero (optional), and anywhere inside page content. 
- Retro
1. Go to this page
https://deploy-preview-151--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose
2. See the textured bar below the hero, and there are 2 more in the ankle
3. Check responsive behavior
- JIRA ticket(s) - GIVCAMP-107
=> GIVCAMP-107 | Textured bar component

components/BlurryPoster/BlurryPoster.styles.tsx, components/BlurryPoster/BlurryPoster.tsx, components/EmbedMedia/EmbedMedia.styles.ts, components/Hero/StoryHeroMvp.styles.ts, components/Hero/StoryHeroMvp.tsx, components/TexturedBar/TexturedBar.tsx
- Support for caption for hero image(s)
- Retro
1. Go to https://deploy-preview-153--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose
2. See the caption appear below the hero, in this case, below the textured bar that is below the hero
3. Go to this story
https://deploy-preview-153--giving-campaign.netlify.app/stories/the-most-wicked-problems
4. See that there's a caption there below the hero too (this time no textured bar)
- JIRA ticket(s) - GIVCAMP-237
=> GIVCAMP-237 | Story Hero caption

components/Masthead/Masthead.styles.ts, components/Masthead/Masthead.tsx
- Remove the sticky header on scrolling up behavior (not great for accessibility)
- Retro
1. Go to https://deploy-preview-154--giving-campaign.netlify.app/
2. Check that the masthead looks just as before
3. Scroll down and back up, check that you don't see the masthead coming back in view as sticky at the top
4. Check a light mode page and see that the masthead also looks ok and also no sticky header coming in on scrolling back up
https://deploy-preview-154--giving-campaign.netlify.app/stories/test-story-hero-white-background-vertical
- Other PRs
=> GIVCAMP-252 | Remove sticky header behavior on scrolling back up

components/ChangemakerCard/ChangemakerCard.styles.ts, components/ChangemakerCard/ChangemakerCard.tsx, components/Homepage/Changemaker.tsx, components/Homepage/TogetherSection.tsx, components/Storyblok/SbHomepageMvp.tsx
- The "Brand video" section near the bottom of the page
- Using animated GIF for MVP (or static image TBD)
- Style update to the Changemaker section
- Retro
1. Go to homepage https://deploy-preview-155--giving-campaign.netlify.app/
2. Scroll down to see this section
NOTE: I'll add more custom animation once I put the new local footer in
- JIRA ticket(s) - GIVCAMP-230
=> GIVCAMP-230 | Homepage "brand video" section

components/ChangemakerCard/ChangemakerCard.styles.ts, components/Homepage/TogetherSection.tsx, components/LocalFooter/LocalFooterMvp.styles.tsx, components/LocalFooter/LocalFooterMvp.tsx
- Add animation to the "Together" section
- Local footer and changemaker cards style updates
- Retro
1. https://deploy-preview-157--giving-campaign.netlify.app/
2. Scroll all the way down to the "Together" section and check out the animation that respond to scroll position
3. In local footer, check that the vertical line in the logo lock up aligns with one of the dividers of the nav below it
- JIRA ticket(s) - GIVCAMP-230
=> GIVCAMP-230 | Together section animation and other misc updates

components/BlurryPoster/BlurryPoster.styles.tsx, components/BlurryPoster/BlurryPoster.tsx, components/Container/Container.tsx, components/EmbedMedia/EmbedMedia.styles.ts, components/Hero/StoryHeroMvp.styles.ts, components/Quote/Quote.styles.ts, components/Quote/Quote.tsx, components/StoryImage/StoryImage.styles.ts, components/StoryImage/StoryImage.tsx, components/StoryImage/index.ts, components/Storyblok/SbSection.tsx, components/Storyblok/SbStoryImage.tsx, components/Storyblok/SbStoryMvp/SbAboveContent.tsx, components/StoryblokProvider.tsx, package-lock.json, package.json, utilities/datasource.ts, utilities/getSbImageSize.ts
- image component + various updates in other components
- Update Decanter and other packages
- Retro
1. https://deploy-preview-158--giving-campaign.netlify.app/stories/charging-ahead-batteries-of-the-future
2. https://deploy-preview-158--giving-campaign.netlify.app/stories/the-second-envelope
Look at the two previews, and see all the image component options, plus layouts such as these 50/50 splits
Check responsive and make sure that the image fills the grid cell when the quote side is longer
- JIRA ticket(s) - GIVCAMP-223
=> GIVCAMP-223 | Story image; layout component options; packages updates

components/FeaturedStories/FeatureMasonry.tsx, components/Grid/Grid.tsx, components/Storyblok/SbText.tsx, components/StoryblokProvider.tsx, utilities/datasource.ts
- This site is going to have a lot of custom story layouts. The regular WYSIWYG kind of limits the heading sizes based on their heading level, eg, a h2 is going to have a certain size - this isn't flexible enough for the highly customized stories. Creating this component that maps to the existing `<Text>` component that takes advantage of all the options, e.g., font modular size, variant, etc
- Retro
1. Go to https://deploy-preview-160--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose
2. Take a look at this h2, and this block of text - they're added on Storyblok using this new SbText component
- JIRA ticket(s) - GIVCAMP-253
=> GIVCAMP-253 Storyblok Text (Typography) component

components/Homepage/Changemaker.tsx, components/Homepage/HomepageSplitHero.styles.ts, components/Homepage/HomepageSplitHero.tsx, components/Homepage/TogetherSection.tsx, components/LocalFooter/LocalFooterMvp.styles.tsx, components/LocalFooter/LocalFooterMvp.tsx, components/Masthead/Masthead.tsx, utilities/config.ts
Misc updates for:
- homepage hero
- logo lockup/domain
- local footer
- quote
- Retro
1. Go to https://deploy-preview-165--giving-campaign.netlify.app/
2. Compare to the latest Figma mock
https://www.figma.com/file/4OP7wBaUzeNRwAhVy4fTQU/Campaign-story-page-layouts?type=design&node-id=570%3A3846&mode=dev&t=NMy167cSV7o0ql31-1
3. Check that the logo in the masthead has been updated to Momentum
3. See that the hero text has been updated
4. Check that the intro text has been updated (checking with design whether we want normal or semibold body copy)
5. Scroll further down to see that the posters and section titles have updated copy and images (except for the square small story cards and the flipping cards - those will be updated later.
6. Scroll to the local footer and check that it has been …
=> GIVCAMP-258 | Homepage hero, logo, local footer, quote updates

components/BlurryPoster/BlurryPoster.tsx, components/Homepage/HomepageSplitHero.tsx, components/Quote/Quote.styles.ts, components/Quote/Quote.tsx, components/Storyblok/SbGrid.tsx, components/Storyblok/SbSection.tsx, components/Storyblok/SbSidebarCard.tsx, components/Storyblok/SbStoryImage.tsx, components/Storyblok/Storyblok.types.ts
- Add options to add background color stops to Storyblok Section wrapper component for background color animation with Framer Motion
- Misc other updates including adding spacing options to Storyblok Grid
- Retro
1. Scroll through this story to see the background color change (starting beneath the larger video in the story) from white to light blue back to white at the end
https://deploy-preview-170--giving-campaign.netlify.app/stories/the-most-wicked-problems
2. Make sure it works on mobile Safari as well
3. Go to https://deploy-preview-170--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose
4. See that there's added spacing below the "Sign up with TypeForm" button
- JIRA ticket(s) - GIVCAMP-251
=> GIVCAMP-251 | Add background color animation option to Storyblok Section

components/Banner/Banner.tsx, components/BlurryPoster/BlurryPoster.tsx, components/ChangemakerCard/ChangemakerCard.tsx, components/Hero/StoryHeroMvp.tsx, components/Homepage/HomepageSplitHero.tsx, components/ImageOverlay.tsx, components/Storyblok/SbStoryCard.tsx, components/Storyblok/SbStoryMvp/SbStoryMvp.tsx
- Update story cards so it can pull the card image and card teaser from a story
- Add width/height attribute to images when appropriate
- Retro
1. Go to https://deploy-preview-173--giving-campaign.netlify.app/stories/from-human-health-to-climate-health
2. Scroll to related stories, and see that this image is showing for the Battery Super Power story. This is added as the "card image" field in the Battery story (not the hero foreground/background)
- JIRA ticket(s) - GIVCAMP-268
=> GIVCAMP-268 | Add support for card image and teaser field for MVP Stories; clean up

components/CreateBloks.tsx, components/Grid/Grid.tsx, components/Storyblok/SbGrid.tsx
- Add option for grid to be an `ul` and grid cells to be `li` (for a11y)
- Retro
1. Go to https://deploy-preview-178--giving-campaign.netlify.app/
2. Look at all the grids of cards (eg, the square story card grids, the 4 changemaker card grid)
3. Inspect the code and see that it's using the HTML `ul` for the grid and each item is wrapped in a `li`
4. Look at code
- JIRA ticket(s) - GIVCAMP-267
=> GIVCAMP-267 | Allow grid to be unordered list

app/sitemap.ts, components/BlurryPoster/BlurryPoster.tsx, components/Storyblok/SbSection.tsx, components/Storyblok/SbTypeform.tsx
- First batch of misc updates
- Exclude pages with noindex=true in the sitemap
- Soonish
1. Go to https://deploy-preview-183--giving-campaign.netlify.app/sitemap.xml
2. Confirm that `/page-not-found` isn't on the sitemap (I set it to noindex=true in Storyblok)
3. Go to https://deploy-preview-183--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose
4. Inspect the code, check that in the hero, the superhead is set to aria-hidden=true
5. Check that the superhead is absorbed into the h1 as screen reader only text
- JIRA ticket(s) - GIVCAMP-225
=> GIVCAMP-225 | misc cleanup and sitemap update

components/Homepage/HomepageSplitHero.tsx
- just copy update
- retro
1. Look at code is probably enough
=> Nojira | high priority intro text update

components/Cta/CtaLink.tsx, components/Hero/BasicHeroMvp.tsx
- Add support for linking to assets uploaded to Storyblok
- tighten padding for basic page hero
1. Go to https://deploy-preview-187--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose
2. Scroll to the banner near the footer
3. Check that the link to the PDF in the button has the assets.stanford.edu domain. Check that you can click on it and go to the pdf.
4. Go to https://deploy-preview-187--giving-campaign.netlify.app/newsletter/sign-up
5. Check out the smaller vertical padding on the hero
- JIRA ticket(s) - …
=> GIVCAMP-275 | Add support for linking to assets; tighten padding for basic page hero

components/Banner/Banner.styles.ts, components/BlurryPoster/BlurryPoster.styles.tsx, components/Bracket/Bracket.styles.ts, components/ChangemakerCard/ChangemakerCard.styles.ts, components/EmbedMedia/EmbedMedia.styles.ts, components/FeaturedStories/FeatureMasonry.tsx, components/Grid/Grid.styles.ts, components/Grid/Grid.tsx, components/Hero/BasicHeroMvp.tsx, components/Hero/StoryHeroMvp.styles.ts, components/Homepage/IdealFellow.tsx, components/Homepage/Intro.tsx, components/Homepage/ThemeSection.tsx, components/LocalFooter/LocalFooter.tsx, components/LocalFooter/LocalFooterMvp.styles.tsx, components/Quote/Quote.styles.ts, components/RichText.tsx, components/Scrollytelling/Scrollytelling.styles.ts, components/SplitPoster/SplitPoster.styles.tsx, components/StoryCard/StoryCard.styles.tsx, components/StoryImage/StoryImage.styles.ts, components/StoryPoC/BrochureStory.tsx, components/StoryPoC/ChatbotStory.tsx, components/Storyblok/SbSection.tsx, components/VerticalPoster/VerticalPoster.styles.ts, package-lock.json, package.json
- Update to Decanter v7.2 which uses TW v3.4.1
- Update children: variant to use the TW out of the box *: which does the same thing (direct children selector)
1. Look at the preview and confirm that things stay the same
=> Tailwind 3.4.1

components/Cta/Cta.styles.ts
- Weird Safari underline hover bug fix
- Retro
- 2
1. Go to the homepage on Safari
2. Hover on the Giving to Stanford link, make sure you see an underline
3. Scroll to local footer and hover on these 3 links under the logo, make sure you see an underline also
4. You can compare on https://dev--giving-campaign.netlify.app where it doesn't work quite right on Safari on hover (strangely it worked on focus). It doesn't seem to like the decoration-transparent class in combination with some other classes
- JIRA ticket(s) - GIVCAMP-227
=> GIVCAMP-227 | Safari underline hover bug fix

app/(editor)/editor/page.tsx, app/(storyblok)/[...slug]/not-found.tsx, app/(storyblok)/[...slug]/page.tsx, app/not-found.tsx, app/page.tsx, netlify.toml, package-lock.json, package.json
- See if this solves the Storyblok caching issue of builds the 'right way'
- Discord announcement: https://discord.com/channels/700316478792138842/704276942236549191/1196338053107687465?fingerprint=746451357124264116&attemptId=4c849cac-f116-4bf6-b947-74a5bfe3b6e4
- Doxn: https://github.com/storyblok/storyblok-js-client#custom-fetch-parameter
- Whenever
- Med/low - Killing the build cache files does the job currently
1. View preview build
2. Make a change to content on storyblok and publish change
3. Rebuild (without clearing cache) the preview space
4. Review changes on the front end to see if the new changes were picked up
5. Review build logs for errors
=> NoJira: Storyblok API Javascript client update to support fetch parameters.

components/ChangemakerCard/ChangemakerCard.styles.ts, components/ChangemakerCard/ChangemakerCard.tsx
- A11y fix for updated changemaker cards
- Comment from SODA:
> Although focus no longer moves to the top of the page, the newly visible text is bypassed.  Move focus to the first content element in the card (the text).
> 
> Note: On Safari with VoiceOver the hidden card content (aria-hidden="true") is still announced.  However, this is a know bug that has not been resolved: https://bugs.webkit.org/show_bug.cgi?id=201887
1. Go to the changemaker cards
2. Use keyboard tab to focus on a card
3. Click enter
4. Check that the focus is moved to the content
5. Tab again and check that the focus is moved back to the "Dismiss" button
6. Confirm that by clicking enter that you can actually dismiss the content
7. Open another card content
8. Click escape and make sure it return focus to the button …
=> GIVCAMP-226 | A11y better focus management for changemaker cards

app/(editor)/editor/page.tsx, app/(storyblok)/[...slug]/not-found.tsx, app/(storyblok)/[...slug]/page.tsx, app/not-found.tsx, app/page.tsx, netlify.toml, package-lock.json, package.json
- Reverts back to killing the data cache on the server filesystem instead of trying to set the no-store on the fetch
- I'm punting on this as it looks like we are in a bit of a pickle and I've banged on this enough already. Looking at the threads there looks to be a couple of issues open with the datacache and static -> dynamic navigation. 
- I'd like to revisit this after the Netlify Next plugin update.
- Reverts: https://github.com/SU-SWS/ood-giving-campaign/pull/192
Issues:
* https://github.com/vercel/next.js/issues/43879
* https://github.com/vercel/next.js/issues/46737
* https://github.com/vercel/next.js/issues/42991
* https://github.com/vercel/storage/issues/213
- When you'd like
- Regular
1. Review code
2. Review preview build
=> GIVCAMP-277: Revert "NoJira: Storyblok API Javascript client update to support fetch parameters

components/HeroIcon/HeroIcon.styles.tsx, components/Homepage/ThemeSection.tsx, components/Homepage/TogetherSection.tsx, components/SocialSharing/SocialSharing.styles.ts, components/SocialSharing/SocialSharing.tsx, package-lock.json, package.json
- Update to the social sharing widget
- Minor package updates and fixups
- Whenever
1. Go to any story, eg
https://deploy-preview-196--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose
2. Click on the first button in the social sharing widget
3. Check that the text "Link copied" shows up above the button and stays for 5 seconds
4. Look at code for accessibility
5. Inspect the email and the Twitter button - check that the white space in the title has been converted to %20
- JIRA ticket(s) - GIVCAMP-225
=> GIVCAMP-225 | Improve social sharing and misc fixups

components/BlurryPoster/BlurryPoster.tsx, utilities/getSbImageSize.ts
- Use the useMediaQuery hook to conditionally render desktop or mobile image for Story Hero/Blurry Poster
- See if it solve the problem of story hero rendering delay.
- Retro
1. Go to stories
2. See if hero image appears right away or if there's a delay (2 second ish)
- JIRA ticket(s) - GIVCAMP-278
=> GIVCAMP-278 | Conditionally render mobile/desktop story hero images

app/page.tsx
- Adds long revalidation time to home page
- Trying to avoid the loading showing up where I can
- Clicking on the logo will be a 'hard' navigation as we have turned off pre-fetching there. 
- Whenever
- Low
=> NoJira: Long cache home page too.

components/BlurryPoster/BlurryPoster.tsx, components/ChangemakerCard/ChangemakerCard.tsx, components/Cta/CtaExternalLink.tsx, components/GlobalFooter/GlobalFooter.tsx, components/Homepage/TogetherSection.tsx, components/RichText.tsx, components/Scrollytelling/Scrollytelling.styles.ts, components/SocialSharing/SocialSharing.styles.ts, components/SocialSharing/SocialSharing.tsx, components/StoryCard/StoryCard.tsx
- SODA fixes (non 3rd party related ones)
- Add support to linking to assets inside WYSIWYG
- Further image size reduction
- Soon
- 5
1. Go to any story or this one:
https://deploy-preview-206--giving-campaign.netlify.app/stories/the-most-wicked-problems
2. Check that the social sharing buttons are wrap in ul/li structure
3. Scroll down to the scrollytelling section with the letter to Elizabeth Warren. Click on the link in the caption to read the PDF and see that it works.
4. Go to this story
https://deploy-preview-206--giving-campaign.netlify.app/stories/the-second-envelope
5. Inspect the hero background image and confirms that it doesn't have a aria-describedby attribute that references the hero caption.
6. Inspect any external links on the site and check that screen reader text "(link …
=> GIVCAMP-226 | SODA a11y fixes and add support to asset link in WYSIWYG

components/Storyblok/SbTypeform.tsx, components/TypeForm/PopUp.tsx
- Add Typeform pop up button style to the button element instead of a wrapper span, so the focus styles get honored.
- Return focus to the pop up button after modal is closed
- Soonish
- 4
1. Go to this story
2. Tab to this button and check that there is focus style (darker red background color, white underline)
3. Open the modal
4. Close the modal with the escape button.
5. Check that the focus is back on the pop up button instead of to the top of the page
- JIRA ticket(s) - GIVCAMP-226
=> GIVCAMP-226 | Typeform a11y fixes

package-lock.json, package.json
- Update @typeform/embed-react to v3.11.0 since they added an aria-label="Close" to the modal close button
https://github.com/Typeform/embed/issues/635#issuecomment-1916508324
- Retro
- 3
1. Go to https://deploy-preview-214--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose
2. Scroll to the "Take my exam" button to open up the typeform modal
3. Inspect the close "x" button
4. Check that you see the aria-label="Close"
- JIRA ticket(s) - GIVCAMP-226
=> GIVCAMP-226 | Update Typeform to latest for modal close button a11y issue

utilities/getPageMetadata.ts
- Update search engine/browser tab title for homepage so it's Home | Stanford Momentum
- Soon (before Sat real launch)
1. Go to https://deploy-preview-220--giving-campaign.netlify.app/
2. Check the HTML head, see that the browser tab title is `Home | Stanford Momentum`, but the og:title is just `Stanford Momentum`
3. Go to any story, check that the browser tab title is `Story Title | Stanford Momentum`, the og:title is just the story title
- JIRA ticket(s) - GIVCAMP-283
=> GIVCAMP-283 | Use "Home | Stanford Momentum" as search engine title for homepage

components/StoryCard/StoryCard.tsx
- Amend the last PR #228 to crop a larger square image if the card is horizontal
- retro
1. Can probably just look at the code
- JIRA ticket(s) - GIVCAMP-288
=> GIVCAMP-288 | Larger image crop for horizontal card variant

app/(editor)/editor/page.tsx
- Per client request: We really only share them with internal team members and leadership, but do rely on them working/being available for many days, sometimes weeks, for review – particularly by leadership.
This opens up the URL and editor to live for a very long time. The risk associated with this is the possibility of someone getting a hold of the API token and using it against the preview URL to see unpublished content. This is a low-risk item to me as they could also use the same API key to query the API directly to get the same content. The preview URL is just a convenient way. One could also just change the timestamp if they knew.
- End of the week?
- Normal
1. Review code
2. Add Preview URL to Storyblok space
3. View content in Storyblok editor
4. Click on the preview button in …
=> NoJira: Remove Editor Token

components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.styles.ts, components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.tsx, components/Storyblok/SbSection/SbSection.styles.ts, components/Storyblok/SbSection/SbSection.tsx
- Add optional CTA(s) region after Section and Homepage Theme/Story Section components
- Retro
- 4
1. Pull down locally and go to test/yvonne-test-volunteer-leadership-summit
2. Scroll down to below the photo section
3. See that you can add CTA(s) at the bottom of the section that are center aligned like this
4. Go to test/home-new-test
5. Scroll to the bottom of the Preparing Citizens section
6. CHeck that you can also add CTA(s) at the bottom
- JIRA ticket(s) - GIVCAMP-304
=> GIVCAMP-304 | Add CTA region to Section and Homepage Theme/Story Section

netlify.toml
- Sets max age to 31536000
- See: https://github.com/SU-SWS/ood_giving_site/pull/402
- End of the month (march)
- low
1. Review preview build headers and look for: `Strict-Transport-Security: max-age=31536000;` in the response headers
=> HSTS set max-age to 31536000

components/Hero/BasicHero.styles.ts, components/Hero/BasicHero.tsx, components/MomentPoster/MomentPoster.styles.ts, components/MomentPoster/MomentPoster.tsx, components/Storyblok/SbBasicPage.tsx, components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.styles.ts, components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.tsx
- Dark overlay (top, middle, bottom gradient stops) and background image blur options for Basic Page Hero
- Improve image optimization for Basic Page Hero
- Retro
- 3
1. Go to https://deploy-preview-243--giving-campaign.netlify.app/initiatives
2. Check that the basic page hero has a custom 3 point gradient
3. Additional existing basic pages heroes to check (whether there is a dark overlay)
https://deploy-preview-243--giving-campaign.netlify.app/newsletter/sign-up
https://deploy-preview-243--giving-campaign.netlify.app/404
3. Pull down locally and go to any test basic page and try out the new hero options (overlay, background blur)
- JIRA ticket(s) - GIVCAMP-294
=> GIVCAMP-294 | Basic Hero overlay options and image optimization

components/Embed/Embed.tsx, components/Embed/index.ts, components/Storyblok/SbEmbed.tsx, components/StoryblokProvider.tsx
- Allows content authors to embed external scripts and markup inline with content
- Provides container controls
- Added new block to content only for now
- TBD permissions to this block type?
End of the sprint
Normal
1. Check out this branch locally and fire up an https dev environment
2. Review the editor at https://app.storyblok.com/#/me/spaces/1005200/stories/0/0/4582847
3. Navigate to the embed script block in the content
4. Review fields, descriptions, and options
5. Navigate to the block library and review the 'Embed Script' component (Atoms -> sbEmbedScript) https://app.storyblok.com/#/me/spaces/1005200/components/145576
6. Try out a few of the options and/or load additional scripts
7. Review code
=> GIVCAMP-289: Inline External Script Loading.

components/BlurryPoster/BlurryPoster.tsx, components/Hero/StoryHeroMvp.styles.ts, components/Hero/StoryHeroMvp.tsx, components/Hero/StoryHeroStacked.styles.ts, components/Hero/StoryHeroStacked.tsx, components/Hero/index.ts, components/Storyblok/SbStoryMvp/SbStoryMvp.tsx, components/Storyblok/Storyblok.types.ts
- New stacked story hero variant
- Retro
- 5
1. Go to Storyblok page `test/test-stories/yvonne-test-arts-feature`
2. Select PR 251 from the Storyblok visual editor
3. Play with the hero options
4. Go to the Netlify preview https://deploy-preview-251--giving-campaign.netlify.app/
5. Look at several existing stories and check that they look the same as they are on production.
- JIRA ticket(s) - GIVCAMP-307
=> GIVCAMP-307 | Stacked story hero variant

components/InitiativeCard/InitiativeCard.styles.ts, components/InitiativeCard/InitiativeCard.tsx, components/MomentPoster/MomentPoster.styles.ts, components/Storyblok/SbInitiativeCard.tsx, components/Storyblok/SbSection/SbSection.tsx
- Horizontal Initiative card variant
- Add square image aspect ratio option
- Retro
- 4
1. Go to Storyblok /initiatives/stanford-arts and select PR 256 from the visual editor URL
2. Scroll to near the bottom and play with the initiative card options with the image aspect ratio and the horizontal card variant
3. Check that this page is the same as live
https://deploy-preview-256--giving-campaign.netlify.app/initiatives
- JIRA ticket(s) - GIVCAMP-292, GIVCAMP-305
=> GIVCAMP-292 GIVCAMP-305 | Horizontal Initiative card and image aspect ratio options

components/EmbedMedia/EmbedMedia.styles.ts, components/Hero/StoryHeroMvp.styles.ts, components/InitiativeCard/InitiativeCard.tsx, components/Parallax/Parallax.tsx, components/Parallax/index.ts, components/Scrollytelling/Scrollytelling.styles.ts, components/StoryImage/StoryImage.styles.ts, components/StoryImage/StoryImage.tsx, components/Storyblok/SbSection/SbSection.styles.ts, components/Storyblok/SbStoryImage.tsx, components/Typography/typography.styles.ts, components/VerticalPoster/VerticalPoster.styles.ts, tailwind/plugins/base/gc-base.js, tailwind/plugins/components/gc-typography.js
- Add parallax option to story image
- Standardize all caption font size and top margin
- Add option to hide a story image
- Retro
- 4
1. Go to storyblok test/test-stories/yvonne-test-arts-feature
2. Pick PR 261 from the visual editor and scroll down to see the images with parallax enabled
3. Enabled reduced motion in the Mac OS or iOS and refresh. Check that the images still shows up but there's no parallax effect.
4. Check out a page with many story images like this and see that the images without parallax still look ok
https://deploy-preview-261--giving-campaign.netlify.app/volunteer-leadership-summit
- JIRA ticket(s) - GIVCAMP-311 GIVCAMP-325
=> GIVCAMP-311 | Add parallax window and hidden options to story image

components/Storyblok/SbBanner.tsx, components/Storyblok/SbBlurryPoster.tsx, components/Storyblok/SbEmbedMedia.tsx, components/Storyblok/SbGrid.tsx, components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.tsx, components/Storyblok/SbMomentPoster.tsx, components/Storyblok/SbScrollytelling.tsx, components/Storyblok/SbSection/SbSection.tsx, components/Storyblok/SbStoryImage.tsx, components/Storyblok/SbVerticalPoster.tsx, components/Storyblok/SbWysiwyg.tsx
- Add option to some components to hide themselves. Client has that functionality on Giving (for Section) and would like the same here.
- Retro
- 2
1. Pull down locally and go to Storyblok on a test page
2. Check that you can hide for example, a Section with the "Hide this section" toggle.
3. Check that the preview still looks normal and nothing is missing.
- JIRA ticket(s) - GIVCAMP-325
=> GIVCMP-325 | Add option to hide some components

components/FeaturedStories/FeatureMasonry.tsx, components/Scrollytelling/Scrollytelling.styles.ts, components/Scrollytelling/Scrollytelling.tsx, components/Storyblok/SbFeatureMasonry.tsx, components/Storyblok/SbScrollytelling.tsx
- Add options for background image entrance for Scrollytelling sections
- misc updates
- Retro
- 3
1. Go to Storyblok and select PR 266 from the visual editor
2. Add a scrollytelling section from the preset into the content region
3. Play with the "Background image entrance" options
4. Go to the Netlify preview of this story: https://deploy-preview-266--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose
5. Scroll to the "Why College" scrolly telling section. Check that the background image still zooms in during the entrance as you scroll
- JIRA ticket(s) - GIVCAMP-296
=> GIVCAMP-296 | Background image entrance options for Scrollytelling sections

components/Cta/Cta.styles.ts, components/Masthead/Masthead.styles.ts, components/Masthead/Masthead.tsx
- Remove the "Make a gift" button from the masthead
- Retro
- 4
1. Look at the preview
2. Check that the "make a gift" button is no longer in the masthead
3. Check responsive
- JIRA ticket(s) - GIVCAMP-330
=> GIVCAMP-330 | Remove make a gift button from Masthead

components/Grid/Grid.styles.ts, components/StoryCard/StoryCard.styles.tsx, components/StoryCard/StoryCard.tsx, components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.styles.ts, components/Storyblok/SbStoryCard.tsx
- List view for Story Cards (for the story landing/filter page)
- Retro
- 4
**Note:** This has been approved by Kerri on the design side. I'll add taxonomy chips in another ticket to all story cards
1. Go to storyblok test/home-new-test
2. Pick PR 272 from the visual editor
3. Look at the first section - these story cards
4. Resize slowly and check all responsive styles
5. Go to https://deploy-preview-272--giving-campaign.netlify.app/ and make sure current story cards look the same as before.
- JIRA ticket(s) - GIVCAMP-333
=> GIVCAMP-333 | Story Card list view style

components/Cta/Cta.styles.ts, components/Scrollytelling/Scrollytelling.tsx, components/StoryCard/StoryCard.styles.tsx, components/StoryCard/StoryCard.tsx, components/Storyblok/SbStory.tsx, components/Storyblok/SbStoryCard.tsx, tailwind/plugins/theme/gc-colors.js, utilities/taxonomyMaps.ts
- Add taxonomy chips (initiative only for now) to all variants of Story Cards
- Add light/dark mode to Story Cards (it was inheriting parent container text color currently so it still sort of work, but this actual light/dark mode selection will modify the variant of the chips also (light/dark)
- Retro
- 6
1. Go to Storyblok `test/home-new-test` and select PR 273 from the visual editor URL
2. See the chips on the horizontal, list, and default (vertical) story card variants
3. Test responsive behavior and see that all chips are left aligned with the card body copy.
4. Go to the newsletter page and look at the light mode cards with the light mode tags. NOTE: Once this is live, we'll change the grid behavior of some of these card grids since the story cards are now too small when they have …
=> GIVCAMP-342 | Add taxonomy chips and light/dark mode to all variants of Story Cards

components/StoryCard/StoryCard.tsx, components/Storyblok/SbStoryCard.tsx, components/Typography/typography.types.ts, utilities/taxonomyMaps.ts
- This gets merged into the integration branch `story-list-pages` after approval
- Add themes to the taxonomy tags
- Content authors will self governed (decided in meeting) to not tag more than 3 items and they will order them in Storyblok
- Initiative tags go before any theme tags
- Retro
- 5
1. Go to https://deploy-preview-290--giving-campaign.netlify.app/ and see the story tags on the story cards.
1. Go to Test -> Home New Test and select PR290 from the visual editor in Storyblok
2. Play around with taxonomies (initiatives and Themes only). Check that they're displayed with initiative tags first, followed by theme tags
3. For a story card, select any heading level except h6, check that the screen reader only tag heading "Story tags:"  level is one level down. Select heading level h6, …
=> GIVCAMP-351 | Add themes to taxonomy in story cards

components/ChangemakerCard/ChangemakerCard.styles.ts
- TW class `whitespace-pre-line ` whitespace has no hyphen in between 🤦🏼‍♀️ 
- Retro
- 1
1. Just looking at code is ok
=> Nojira | no hyphen between TW class whitespace

app/(editor)/editor/page.tsx, app/(storyblok)/[[...slug]]/page.tsx, components/Cta/Cta.types.ts, components/Cta/CtaExternalLink.tsx, components/Cta/CtaNextLink.tsx, components/Hero/StoryListHero.styles.ts, components/Hero/StoryListHero.tsx, components/Storyblok/SbCta.tsx, components/Storyblok/SbStoryCard.tsx, components/Storyblok/SbStoryFilterPage/SbStoryFilterPage.styles.ts, components/Storyblok/SbStoryFilterPage/SbStoryFilterPage.tsx, utilities/taxonomyMaps.ts
- Fetch stories to display in list view in story filter pages - top level at /stories (display all stories) and the filtered ones inside the directory /stories/list/
- Add skip link to skip past story filter menu on story filter pages (will work on mobile etc in another ticket)
- Allow the Storyblok CTA to have spacing top and bottom options
- Soon would be nice
- 7
1. Go to Storyblok /stories page
2. Choose the PR 301 from the visual editor URL list
3. Use the tab key on the keyboard and see how the skip link appears for the story filter nav
4. Verify that the story list below the featured story (the large horizontal card) is displaying all published stories except for the featured story
5. Check that the stories are in reverse chronological order (featured story not part of this as it's …
=> GIVCAMP-358 | Add filtered story lists

components/BlurryPoster/BlurryPoster.tsx, components/Cta/Cta.styles.ts, components/Hero/StoryHeroStacked.tsx
- Kerri said let's get rid of the black version of story tags and use the dark grey one for story heroes as well
- Have tags next to each other instead of one on each row for story heroes
- Retro
1. Go to https://deploy-preview-305--giving-campaign.netlify.app/stories/an-ideal-approach
2. Story tags should now be dark grey instead of black and they are next to each other
3. Go to https://deploy-preview-305--giving-campaign.netlify.app/stories/cartographer-of-cancer
4. Same check as step2
- JIRA ticket(s) - GIVCAMP-362
=> GIVCAMP-362 | Story tag revision

utilities/getPageMetadata.ts
- Use hero image from the hero in the hero picker as the og image for metadata if there is one (for Story Filter page for example)
- Use top level component type to determine og type for metadata
- Retro
- 3
1. I have quickly published some pages (with noindex=true) last night to test and this behaved as expected
2. This is the screen cap I took - story filter pages are using the image from the hero selected in the hero picker field as the OG image
3. Go to any non story pages, eg. homepage, og type in the head metadata should be "website"
https://deploy-preview-322--giving-campaign.netlify.app/
4. Go to any story pages, eg, https://deploy-preview-322--giving-campaign.netlify.app/stories/not-her-first-rodeo
og type should be "article"
- JIRA ticket(s) - GIVCAMP-369
=> GIVCAMP-369 | Story Filter SEO update

app/(editor)/editor/page.tsx, app/(storyblok)/[[...slug]]/page.tsx, utilities/data/getStoryData.ts, utilities/data/getStoryList.ts, utilities/data/types.d.ts
- For use in the (editor) route group, we want to always pull in the draft version of the story data.
- In the getStoryList function, it is ok to always use the published version (this doesn't seem to cause an API permission issue)
- July 11
- 7
=> Always use draft for story data when in storyblok editor

components/StoryImage/StoryImage.styles.ts, components/StoryImage/StoryImage.tsx, components/StoryImage/index.ts, components/Storyblok/SbSection/SbSection.styles.ts, components/Storyblok/SbSection/SbSection.tsx, components/Storyblok/SbStoryImage.tsx, components/WidthBox/WidthBox.tsx, package.json
- Provide options to add background colors to captions in Section and Story Image components
- Add padding to caption if background color is selected for Image compnent
- Retro
- 4
1. Go to Test -> Yvonne Test Caption - The Power of Art in storyblok and pick PR 330 from the visual editor.
2. Scroll down to see how these examples are possible
- JIRA ticket(s) - GIVCAMP-373
=> GIVCAMP-373 | Add caption background options to Section and Story Image

components/StoryCard/StoryCard.tsx, components/Storyblok/SbStoryFilterPage/SbStoryFilterPage.styles.ts, components/Storyblok/SbStoryFilterPage/SbStoryFilterPage.tsx, components/Storyblok/SbStoryListNav/SbStoryListNav.tsx
- Display "Show all stories" button when there are more than 10 stories (excluding the featured one).
- After the button is click, it changes to a "Back to top" button that takes users to the filter menu heading.
- NOTE: Client likes the max number of stories to be 10 before the "Show all stories" button is displayed.
- retro
- 4
1. Go to https://deploy-preview-332--giving-campaign.netlify.app/stories
2. scroll to the end of the list of stories and test the "Show all stories" button
3. It should show all stories and if using keyboard, focus on the 11th story after the button is clicked.
4. After that, it should become a "Back to top" button
5. Click that and it should bring users back to the filter menu heading.
- JIRA ticket(s) - GIVCAMP-372
=> GIVCAMP-372 | Show all stories functionality on story filter pages

app/(storyblok)/[[...slug]]/layout.tsx, app/layout.tsx
- Moves heap script to load on the SB pages and not on the editor
- Whenever
- Regular
1. Check out this branch
2. Set your `.env` file `CONTEXT` variable to `production`
3. Navigate to the [home page](http://localhost:3000/) on your local
4. Validate that the heap script loads by looking at your network tab requests (look for `heap-2306378928.js` or similar)
5. Do the same with an [interior page](http://localhost:3000/initiatives)
6. Navigate to storyblok and [load a page in the editor](https://app.storyblok.com/#/me/spaces/1005200/stories/0/0/8269210?env=Localhost) using the Localhost URL
9. Look at your network tab and confirm that the heap script does not load
- GIVCAMP-356
=> GIVCAMP-356: Move Heap script so that it doesnt load on the editor page.

components/Cta/CtaLink.tsx, components/GAProvider.tsx, components/Storyblok/SbBasicCard.tsx, components/Storyblok/SbEmbedMedia.tsx, components/Storyblok/SbEventBanner.tsx, components/Storyblok/SbGrid.tsx, components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.tsx, components/Storyblok/SbScrollytelling.tsx, components/Storyblok/SbSection/SbSection.tsx, components/Storyblok/SbSidebarCard.tsx, components/Storyblok/SbText.tsx, components/Storyblok/SbWysiwyg.tsx
- The goal of this ticket is to allow adding ids to some components (Section was the one that was asked, but adding to more components due to the way it's used). Also, confirm that anchor link is working for CTA component and links in WYSIWYG.
- Add id option to 10 components
- If `cached_url` is home in `CtaLink`, set it to empty string (the / is added afterwards in another statement). Note: In some cases, linking to the home page will result in cached_url as `/`. Actually I believe this is the case before, but I found that sometimes it can be `home`, so adding this check to replace `home`. 
- Retro
- 6
1. I've published a couple test pages to test this. They're now unpublished, but you can see the preview build here:
https://deploy-preview-339--giving-campaign.netlify.app/test/test-stori …
=> DS-853 | Add id options to 10 storyblok components; update CtaLink

app/(storyblok)/[[...slug]]/page.tsx, next.config.mjs, utilities/data/getStoryblokRedirects.mjs
- Adds redirects to website
- End of sprint
- Normal
1. Navigate to the following URLs
2. https://deploy-preview-357--giving-campaign.netlify.app/this-is-just-a-test
3. Validate you are redirected to `/changemakers`
10. Create and modify the redirects in [Storyblok](https://app.storyblok.com/#/me/spaces/1005200/stories/0/0/index/13131448)
11. Create a new redirect
12. Try putting in some garbage into the fields to see if the regex catches it
- [DS-918](https://stanford.atlassian.net/browse/DS-918)
- [DS-956](https://stanford.atlassian.net/browse/DS-956)
- [DS-940](https://stanford.atlassian.net/browse/DS-940)
- https://github.com/SU-SWS/ood-stanford-tour/pull/28
=> DS-918: Storyblok Redirects.

.github/pull_request_template.md, components/AnnotatedImage/AnnotatedImage.styles.ts, components/AnnotatedImage/ImageHotspot.tsx, components/ChangemakerCard/ChangemakerCard.styles.ts, components/ChangemakerCard/ChangemakerCard.tsx, components/RichText.tsx, components/Storyblok/SbCardWysiwyg.tsx, components/Storyblok/SbChangemakerCard.tsx
- Use modals for changemaker card content for all breakpoints
- Soon
- 6
1. Go to https://deploy-preview-373--giving-campaign.netlify.app/changemakers
2. Click on a few of the changemaker cards (both horizontal and vertical variants), check that they open up a modal
3. Check that you can use escape key or click outside the modal to close it
4. Check that focus trap works
5. Test on the phone if possible
- JIRA ticket(s) - DS-989
=> DS-989 | Use modals for changemaker card content for all breakpoints

components/Storyblok/SbCardWysiwyg.tsx
- Use digital red xlight for link color as default if the card WYSIWYG is using the light text mode
- Retro
- 5
1. Go to this page and scroll to the bottom of the story where this card is
2. Check that the link color is digital red xlight
3. Compare to current live where it's using the darker digital red which is not accessible
https://momentum.stanford.edu/stories/agree-to-disagree
=> NOJIRA | Add default link color for light text mode for card WYSIWYG

components/EmbedMedia/EmbedMedia.styles.ts, components/EmbedMedia/EmbedMedia.tsx, components/Storyblok/SbEmbedMedia.tsx
- Add Preview Image field to the Embed Media component because React Player pulls the low res thumbnail (600px) as the preview image if using their "light" mode (shows the preview image with an icon instead of the player on page load)
- Sooner would be nice
- 6
1. Go to the live site and look at the video preview of this story, and confirm that it is a low res image:
https://momentum.stanford.edu/stories/into-the-future
2. Go to Momentum Storyblok `Momentum/Test/Yvonne Test Video Preview`
3. Select PR 382 from the visual editor URL
4. Scroll down to see that both of the videos on the page have high res preview images that were selected in storyblok
5. The first video is Vimeo, 2nd is Youtube with a 1x1 aspect ratio. Check that the image fills the container and that the play icon …
=> DS-1102 | Allow adding custom preview image for Embed Media video light mode

components/ChangemakerCard/ChangemakerCard.styles.ts, components/ChangemakerCard/ChangemakerCard.tsx, components/Storyblok/SbChangemakerCard.tsx
- This is a siteimprove suggestion https://stanford.atlassian.net/browse/DS-1115
- Headline for “Changemaker Card” needs text (not heading) option. If there’s no text other than the headline, the headline must not be a heading. 
- Retro
- 5
1. Go to https://deploy-preview-388--giving-campaign.netlify.app/initiatives/undergraduate-financial-aid
2. Look at the Changemaker Cards in question and check that the "headings" are no longer headings
- JIRA ticket(s) - DS-1115
=> DS-1115 | A11y: Don't use heading for changemaker cards because there is no content

components/ChangemakerCard/ChangemakerCard.styles.ts, components/ChangemakerCard/ChangemakerCard.tsx, components/Scrollytelling/Scrollytelling.tsx
- Use container query so that Changemaker Cards look good in a 2-col grid for all breakpoints
- Modify responsive aspect ratio of horizontal changemaker cards in the mid-range breakpoints
- Retro
- 5
1. Go to https://deploy-preview-396--giving-campaign.netlify.app/test/test-changemakers
2. Look at the 2-up horizontal, 1-up horizontal and vertical changemaker cards and check the font size and everything looks proportional at all breakpoints
- JIRA ticket(s) - DS-1148
=> DS-1148 | Support 2-up Changemaker Cards

components/Storyblok/Storyblok.types.ts, components/Tabs/Tabs.styles.ts, components/Tabs/Tabs.tsx
- Add superheading field to Tab items
- Allow user to choose whether to use tab label for superheading or heading
- Code optimization
- Retro
- 6
1. Go to https://deploy-preview-399--giving-campaign.netlify.app/test/yvonne-test-agenda-update
2. Check that all the tab groups are working correctly
3. Check that in the first tab group, the tab labels are used as the big Serif headings in each tab item
4. Check that in the other tab group, the tab labels can be used as either heading or superheading.
5. Go to https://deploy-preview-399--giving-campaign.netlify.app/test/yvonne-test-agenda-update#agenda-3-240-pm-connect--break
6. Check that it opens up the correct tab and scrolls to the right place
7. Go to the above link on mobile and make sure that it scrolls to the correct section
- JIRA …
=> DS-1505 | Allow user to use tab label for heading or superheading; optimization

components/Storyblok/SbStoryCard.tsx, components/Storyblok/SbStoryFilterPage/SbStoryFilterPage.tsx, components/Storyblok/SbStoryMvp/SbStoryMvp.tsx, components/Tabs/Tabs.tsx, utilities/data/getStoryList.ts, utilities/data/types.d.ts, utilities/taxonomyMaps.ts
- Support school taxonomy tags and filter pages
- Remove setTimeout in Tabs component
- Retro
- 6
1. See the top level filter page
https://deploy-preview-401--giving-campaign.netlify.app/stories
The 4 school pages with stories (i'll publish the other 3 with no stories currently as well, since Alexis said go ahead and publish and she'll tag stories to them)
https://deploy-preview-401--giving-campaign.netlify.app/stories/list/graduate-school-of-business
https://deploy-preview-401--giving-campaign.netlify.app/stories/list/stanford-doerr-school-of-sustainability
https://deploy-preview-401--giving-campaign.netlify.app/stories/list/school-of-humanities-and-sciences
https://deploy-preview-401--giving-campaign.netlify.app/stories/list/school-of-medicine (edited)
2. Check that they're showing …
=> DS-1138 | Add support for School taxonomy tags and filter pages

components/EventBanner/EventBanner.styles.ts, components/EventBanner/EventBanner.tsx, package-lock.json, package.json, utilities/getProcessedImage.ts
- While I was sync-ing Momentum changes to Tour, I discovered small things that I want to bring from Tour back to Momentum.
- Update `getProcessedImage` to not use Storyblok image service stuff on svgs
- Update Event Banner (a11y and style fix up)
- Update `@types/node`
- Retro
- 4
1. Look at code and preview
2. Go to https://deploy-preview-407--giving-campaign.netlify.app/experience-the-moment
3. See that the druk headings are left aligned whether there is a date or not on the event banner
4. Inspect the superheading and see that it's a h2 with SR only text of the Druk heading following the visible superheading text.
=> Nojira | Sync tour changes

components/GlobalFooter/GlobalFooter.styles.ts, components/GlobalFooter/GlobalFooter.tsx, components/Logo/StanfordLogo.styles.ts
- Change global footer to black
- Remove digital red stanford logo option
- Retro
- 5
1. https://deploy-preview-410--giving-campaign.netlify.app/
Check that the global footer is black
- JIRA ticket(s) - DS-1683
=> DS-1683 | Remove digital red logo option and change global footer to black

components/EmbedMedia/EmbedMedia.tsx, utilities/getNumBloks.ts
- Add `role="button"` to the clickable div when EmbedMedia preview mode is on (I can't change the HTML element so this is a compromise to make it accessible)
- Better handling when space key is pressed while focused on the preview (so it doesn't scroll down the page - should behave like enter key)
- Update `getNumBloks`
- Soon
- 5
1. Go to https://deploy-preview-411--giving-campaign.netlify.app/test/yvonne-test-video-preview-a11y
2. There are 3 embed media on the page. Only the first 2 are using the preview mode. The 2nd one has a custom preview image while the 1st one uses the default. Inspect the first two players using the preview mode. Check that the `div` has `role="button"`  as an attribute.
3. Press the space bar while you're focused on the preview, check that it plays the video …
=> A11y | DS-1510 | Add role="button" to clickable video preview wrapper

components/BlurryPoster/BlurryPoster.tsx, components/Container/Container.types.ts, components/EmbedMedia/EmbedMedia.styles.ts, components/EmbedMedia/EmbedMedia.tsx, components/FeaturedStories/FeatureMasonry.styles.ts, components/FeaturedStories/FeatureMasonry.tsx, components/Hero/StoryHeroMvp.tsx, components/Hero/StoryHeroStacked.tsx, components/InitiativeCard/InitiativeCard.styles.ts, components/Media/Caption.tsx, components/Media/MediaWrapper.styles.ts, components/Media/MediaWrapper.tsx, components/Scrollytelling/Scrollytelling.tsx, components/Storyblok/SbSection/SbSection.styles.ts, components/Storyblok/SbSection/SbSection.tsx
- Caption related a11y update and other fixups. Other than removing the `aria-describedby` in the story hero images, previously I created a reusable `Caption` component which uses the `figcaption` element as the wrapper. I ended up using it in components that are not `figure` elements but forgot that I need to provide an option so the Caption wrapper is a div instead of a figcaption. This PR fixes that.
- Initiative Card CTA fixup
- Soon
- 5
1. Go to https://deploy-preview-414--giving-campaign.netlify.app/stories/outrunning-the-next-pandemic
2. Check that in the story hero, both the foreground and background images don't have an `aria-describedby` attribute anymore
3. Inspect the caption below the story hero, check that it's a `div` and not a `figcaption`
4. GO to …
=> A11y | DS-1508 | Caption update; Initiative Card CTA fixup

components/Cta/CtaLink.tsx
- Do not render empty or invalid attributes in external or asset CTALink
- Soon
- 5
1. Go to https://deploy-preview-416--giving-campaign.netlify.app/initiatives
2. Inspect the link on the first card which is an asset link
3. Check that it doesn't show fieldtype="multilink" and empty id as attributes anymore
4. Inspect the "Visit IMA" external link on the 3rd card
5. Check that it doesn't show fieldtype="multilink" and empty id as attributes anymore
6. Pull down branch and go to Storyblok Initiative page
7. Using the Visit IMA link as an example, if you add custom attributes (some empty), check that the link only renders the non empty custom attributes. For example
=> Nojira | Do not render empty or undesired props in external links/asset links
