SU-SWS/ood-giving-campaign

package-lock.json, package.json
- Overrides deps deps
- See: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
=> GIVCAMP-000: Override deps.

package-lock.json, package.json, src/components/RichText.tsx, src/components/Storyblok/Teaser.tsx
- Add rich text renderer
- retro
1. Look at code and homepage example components (Teaser)
- JIRA ticket(s) - GIVCAMP-57 part of GIVCAMP-33
=> GIVCAMP-57 | Typescript rich text renderer

src/components/Layout.tsx, src/components/Logo/Logo.styles.ts, src/components/Logo/Logo.tsx, src/components/Logo/index.ts, src/components/Masthead/Masthead.styles.ts, src/components/Masthead/Masthead.tsx, src/components/Masthead/index.ts, src/components/StanfordLogo/StanfordLogo.styles.ts, src/components/StanfordLogo/StanfordLogo.tsx, src/components/Storyblok/SbLogo.tsx, src/components/Storyblok/SbSection.tsx, src/components/Typography/typography.styles.ts, src/pages/index.tsx, src/pages/{storyblokEntry.full_slug}.tsx
- Create the horizontal and stacked variant of the Stanford On Purpose lock up
- Retro
1. Look at the preview to see the 2 logo variants (horizontal in the temp masthead and the stacked one in the light section)
- JIRA ticket(s) - GIVCAMP-62
=> GIVCAMP-62 | Horizontal and stacked On Purpose logos

src/components/NumberCounter.tsx, src/pages/index.tsx
=> GIVCAMP-73 | Animated Number Counter POC

src/components/Hero/HomepageHero.tsx, src/components/Layout.tsx, src/components/Masthead/Masthead.tsx, src/pages/index.tsx
=> GIVCAMP-54 | POC Add animated vertical line that grows on scroll

src/components/SkipLink.tsx, src/components/Typography/Heading.tsx, src/components/Typography/Paragraph.tsx, src/components/Typography/Text.tsx, src/components/WidthBox.tsx/WidthBox.styles.ts, src/components/WidthBox.tsx/WidthBox.tsx, src/components/WidthBox.tsx/index.ts, src/hooks/useHasMounted.ts, src/utilities/getSbImageSize.ts
- WidthBox component fixup
- add useHasMounted hook which we might need later for the Gatsby/React hydration issue
- add SkipLink
- Retro
=> Nojira | SkipLink; Component cleanup; useHasMounted hook for hydration issue

src/components/Hero/HomepageHero.tsx, src/components/HeroIcon/HeroIcon.styles.tsx, src/components/ImageOverlay.tsx, src/pages/index.tsx, src/utilities/externalLinks.ts, src/utilities/getMaskedAsset.ts, src/utilities/getProcessedImage.ts
- Testing proto video background with play/pause functionality
- Some responsive behavior
- will finetune and extract into component later if client/Kerri approves
- Retro
1. Look at the preview
2. Check that the play/pause button works
3. Check that it plays on mobile (for supported devices)
- JIRA ticket(s) - GIVCAMP-86
=> GIVCAMP-86 | Add proto video background test

src/tailwind/plugins/base/gc-base.js, src/tailwind/plugins/theme/gc-screens.js
- Base font size for this project. Settled this with @kerri-augenstein today 😄 
- Tried the TW breakpoints but decided to use the Decanter one for now - no change there.
- Retro
2. Check that the new body font size is applied
=> Nojira | Change base font size

.github/workflows/release.yml, README.md
- Auto release workflow
1. Look at code?
- JIRA ticket(s) - GIVCAMP-24
=> GIVCAMP-24 | Release workflow

.github/release-drafter.yml, package.json
- Add release-drafter.yml file for the release workflow (turns out I need this or it holds up the release workflow 😬 )
1. 
- JIRA ticket(s) - GIVCAMP-24
=> Nojira | Add release-drafter.yml

src/components/Bracket/Bracket.styles.ts, src/components/Bracket/Bracket.tsx, src/components/Bracket/BracketCurve.tsx, src/components/BracketCard/BracketCard.styles.ts, src/components/BracketCard/BracketCard.tsx, src/components/Cta/Cta.styles.ts, src/components/Storyblok/SbSection.tsx
- XS-MD styles for braket cards
- Retro
1. [Check out this branch or go to the netlify preview](https://deploy-preview-52--giving-campaign.netlify.app/)
2. Look at the bracket card at XS to MD breakpoint
XS only
SM and up
- JIRA ticket(s) - GIVCAMP-106
=> GIVCAMP-106 | Mobile bracket card

src/components/BracketCard/BracketCard.tsx
- slide in animation for bracket card image
1. Look at preview
- JIRA ticket(s) - GIVCAMP-106
=> GIVCAMP-106 | Add slide in animation for image for bracket card

.eslintignore, README.md, src/components/Hero/HomepageHero.tsx, src/pages/index.tsx, src/pages/{storyblokEntry.full_slug}.tsx
- Instead of building pages using the starter Storyblok Page component, we've added Basic Page on Storyblok, and this PR is the start of a WIP to support that
- Added some animation and video changes for branding update demo purposes.
- Retro
1. Look at the preview and see that the page renders with all the components that were added on Storyblok
2. See that the test Stanford video has been swapped.
- JIRA ticket(s) - GIVCAMP-103 (just the beginning)
=> GIVCAMP-103 | WIP Basic page proto + filter saturation animation + Stanford vid loop POC

src/components/Hero/HomepageHero.tsx, src/components/VerticalCard/VerticalCard.tsx, src/utilities/gradients.ts
- Just some homepage quick branding related updates to make it more Stanford-y. This is to prep it for client's demo to stakeholder.
1. Look at the preview
=> Nojira | Update homepage hero for branding adjustment demo

src/components/Bracket/Bracket.styles.ts, src/components/BracketCard/BracketCard.styles.ts, src/components/Container/Container.styles.ts, src/components/Cta/Cta.styles.ts, src/components/Intro/Intro.tsx, src/components/Parallax/Parallax.tsx, src/components/RichText.tsx, src/components/StanfordLogo/StanfordLogo.styles.ts, src/components/Temporary/DemoContent.tsx, src/components/Typography/typography.styles.ts, src/components/VerticalCard/VerticalCard.styles.tsx, src/pages/index.tsx, src/pages/{storyblokEntry.full_slug}.tsx, src/utilities/datasource.ts
- What the title says
1. Look at the preview and the code
- JIRA ticket(s) - GIVCAMP-118
=> GIVCAMP-118 | Replace  SAA Black color with Campaign (gc) Black color

src/components/Intro/Intro.tsx, src/components/Shapes/Triangle.tsx, src/components/Shapes/index.ts, src/components/SplitPoster/PosterContent.tsx, src/components/SplitPoster/SplitPoster.styles.tsx, src/components/SplitPoster/SplitPoster.tsx, src/components/Storyblok/SbSection.tsx, src/components/Storyblok/SbSplitPoster.tsx, src/components/Temporary/FindPurposeSection.tsx, src/components/Temporary/ThemeSection.tsx, src/pages/index.tsx, src/tailwind/plugins/components/gc-typography.js
- Build "Find Your Purpose" section for stakeholder demo
- Large offset option for split poster
- Retro
1. Look at "Find Your Purpose" section on the homepage
- JIRA ticket(s) - GIVCAMP-124
=> GIVCAMP-124 | Find Your Purpose section for homepage stakeholder demo

src/components/Banner/Banner.tsx, src/components/Banner/index.ts, src/components/Temporary/FindPurposeSection.tsx, src/pages/index.tsx
- POC ankle banner for stakeholder review
- Note: all of these POC components will need to be connected to Storyblok later. Also, they're done very quickly just for Patrick to demo to Stakeholder so think of them as very rough drafts with no or very little responsive treatments.
- Retro
1. Scroll to the bottom to look at the ankle banner
- JIRA ticket(s) - GIVCAMP-123
=> GIVCAMP-123 | Ankle banner POC for stakeholder review

src/components/Cta/Cta.styles.ts, src/components/Temporary/FindPurposeSection.tsx, src/components/Temporary/ThemeSection.tsx, src/components/VerticalCard/ThemeCard.tsx
- Theme section intro update
- Retro
1. Look at the theme intro
- JIRA ticket(s) - GIVCAMP-121
=> GIVCAMP-121 | Theme intro update; CTA size update

src/components/BracketCard/BracketCard.styles.ts, src/components/Grid/Grid.styles.ts, src/components/Hero/HomepageHero.tsx, src/components/Temporary/DemoContent.tsx, src/components/Temporary/FindPurposeSection.tsx, src/components/Temporary/ProgressStories.tsx, src/components/Temporary/ThemeSection.tsx, src/utilities/colorPalettePlugin.ts
- In the theme section, morph the down triangles into bars below each theme heading
- Retro
1. Look at the preview and scroll to the theme section to see the triangle animation on scroll
- JIRA ticket(s) - GIVCAMP-116
=> GIVCAMP-116 | Animate triangles to bars in theme section

src/components/BracketCard/BracketCard.styles.ts
- Misc fixup for Bracket cards
- Retro
1. Scroll down the preview to see t
he bracket cards.
2. Check that most parts of the cards is now a clickable link
3. Check the image zoom effect when hocus
4. Check that for SM breakpoint and up, the card fits within the centered container (see comment called out below)
=> Nojira | Fix stretched links and other minor things on bracket cards

package-lock.json, package.json, src/components/Bracket/Bracket.styles.ts, src/components/BracketCard/BracketCard.styles.ts, src/components/Cta/Cta.styles.ts, src/components/VerticalCard/VerticalCard.styles.tsx
- Upgrade to Decanter v7.0.0 because errrr soft launch 😂 
- Retro
1. Go to the preview and scrolling through the page, check that things look the same
2. Look at things called out
- JIRA ticket(s) - GIVCAMP-155
=> GIVCAMP-155 | Upgrade to Decanter v7.0.0

src/components/Hero/StoryHero.styles.ts, src/components/Hero/StoryHero.tsx, src/components/Hero/index.ts, src/components/InitiativeCard/InitiativeCard.styles.ts, src/components/Layout.tsx, src/components/Masthead/Masthead.tsx, src/pages/index.tsx, src/pages/{storyblokEntry.full_slug}.tsx, src/tailwind/plugins/theme/gc-colors.js, tailwind.config.ts
- Part 1 of Story Hero component
- Retro
1. Look at these previews
horizontal:
https://deploy-preview-95--giving-campaign.netlify.app/stories/harnessing-satellite-imagery-ai-to-help-fight-poverty/
vertical:
https://deploy-preview-95--giving-campaign.netlify.app/stories/accelerators-solutions-sped-up/
no image:
https://deploy-preview-95--giving-campaign.netlify.app/stories/i-m-a-story-with-no-hero-image/
3. There's more to come, but I'm going to merge this in first and get the nextjs PR in, then continue after that.
- JIRA ticket(s) - GIVCAMP-147
=> GIVCAMP-147 | Story hero

components/Cta/Cta.styles.ts, components/Homepage/BlockBanner.tsx, components/Homepage/BlockPoster.tsx, components/Homepage/ProgressStorySection.tsx, components/ImageOverlay.tsx, components/InitiativeCard/InitiativeCard.styles.ts, components/Storyblok/SbHomepage.tsx, components/VerticalCard/VerticalCard.styles.tsx, components/VerticalCard/VerticalCard.tsx, components/WordBlock/WordBlock.styles.ts, components/WordBlock/WordBlock.tsx, components/WordBlock/index.ts, tailwind/plugins/theme/gc-containers.js, utilities/datasource.ts, utilities/routes.ts
- WordBlock component (that can be reused later)
- Block Poster component for the homepage
- Retro
1. Go to https://deploy-preview-101--giving-campaign.netlify.app/
2. Scroll to the block poster and check that it looks like this
- JIRA ticket(s) - GIVCAMP-170
=> GIVCAMP-170 | Homepage wordblock banner; WordBlock component

components/Homepage/BelowBlockBanner.tsx, components/PortraitCard/PortraitCard.styles.ts, components/PortraitCard/PortraitCard.tsx, components/PortraitCard/index.ts, components/Storyblok/SbHomepage.tsx, components/Storyblok/SbPortraitCard.tsx, components/StoryblokProvider.tsx, components/WordBlock/WordBlock.styles.ts
- Portrait card component initial batch
- Custom homepage section with the quote cards
- Not doing more work until we know new direction
- Note: some of the elements aren't really styled right now. On hold till we know what to do.
- Retro
1. Go to the preview and scroll to these cards
- JIRA ticket(s) - GIVCAMP-171
=> GIVCAMP-171 | Portrait card and homepage section

components/Grid/Grid.tsx, components/ScrollyTelling/ScrollyTelling.tsx, components/Storyblok/SbStory.tsx, package-lock.json, package.json, utilities/colorPalettePlugin.ts
- NYT style scrollytelling story POC
- Retro
1. Look at https://deploy-preview-107--giving-campaign.netlify.app/stories/immersive-featured-story-test
- JIRA ticket(s) - GIVCAMP-107
=> GIVCAMP-180 | Scrollytelling POC

components/ImageOverlay.tsx, components/ScrollyTelling/ScrollyFullwidth.tsx, components/ScrollyTelling/ScrollyTelling.tsx, components/Storyblok/SbStory.tsx, components/Temporary/Paragraphs.tsx
- Fullwidth scrollytelling ideas
- Retro
1. https://deploy-preview-108--giving-campaign.netlify.app/stories/immersive-featured-story-test
2. See the first 2 full width content sections
- JIRA ticket(s) - GIVCAMP-181
=> GIVCAMP-181 | Fullwidth scrollytelling

components/Bookshelf/Book.tsx, components/Bookshelf/Bookshelf.tsx, components/Storyblok/SbStory.tsx, components/StoryblokProvider.tsx
- POC "bookshelf" idea
- Retro
1. Look at preview 
https://deploy-preview-109--giving-campaign.netlify.app/stories/poc-bookshelf-idea
- JIRA ticket(s) - GIVCAMP-182
=> GIVCAMP-182 | Bookshelf POC

components/Animate/AnimateInView.tsx, components/Animate/AnimationMap.ts, components/StoryPoC/MulticolumnStory.tsx, components/Storyblok/SbStory.tsx, components/Typography/typography.styles.ts
- Another story idea (multiple columns plus images and quotes animating from blurry to sharp), plus smooth background color change that's linked to scroll position in the middle section.
- Retro
1. Look at this story https://deploy-preview-110--giving-campaign.netlify.app/stories/poc-whereas-recognition-of-the-inherent-dignity
- JIRA ticket(s) - GIVCAMP-183
=> GIVCAMP-183 | Multicolumn story poc

app/[...slug]/page.tsx, app/page.tsx
- Add resolve relations to `StoryblokStory` component (provide by the @storyblok/react package) so that when references to stories are added on a page (eg, story card with a single option picker field that picks the story), in the visual editor, when a user makes any changes, the story references don't disappear.
- Note: I got this trick from the Storyblok Discord - it's not documented in the tutorial.
https://discord.com/channels/700316478792138842/700322763356897280/1142061735600210001
- Retro
1. Pull down this branch
2. Go to the /about-test page in Storyblok
3. Make any changes on the page
4. Check that the story cards don't disappear.
- JIRA ticket(s) - GIVCAMP-185
=> GIVCAMP-185 | Add resolve relations to bridgeOptions for StoryblokStory

app/[...slug]/page.tsx, components/Animate/AnimationMap.ts, components/StoryPoC/ChatbotStory.tsx, components/Storyblok/SbStory.tsx
- "Fake it till you make it" chatbot interaction
- It allows user to make a choice and conditionally display content at the end
- Retro
Note: This is held together by duct tape 🤣 But it is just a POC so if they like it, I'll clean it up for sure.
1. https://deploy-preview-114--giving-campaign.netlify.app/stories/poc-ai-chatbot-story
2. Scroll to the "chatbot" interface and give it a try
- JIRA ticket(s) - GIVCAMP-187
=> GIVCAMP-187 | Fake Chatbot PoC

components/StoryPoC/VideoScrollStory.tsx, components/Storyblok/SbStory.tsx, utilities/colorPalettePlugin.ts
- Started off playing with video scrubbing - decided that's a bad idea and moved onto background video + CSS blend mode testing for a visual experience
- Retro
1. See https://deploy-preview-115--giving-campaign.netlify.app/stories/poc-video-scrolling-story
2. See notes
- JIRA ticket(s) - GIVCAMP-186
=> GIVCAMP-186 | Background video play with blend mode story PoC

components/AnimatedText/AnimatedText.tsx, components/Bookshelf/Book.tsx, components/Cta/Cta.styles.ts, components/HeroIcon/HeroIcon.styles.tsx, components/Masthead/Masthead.tsx, components/StoryPoC/BrochureChapter2.tsx, components/StoryPoC/BrochureStory.tsx, components/StoryPoC/ProgressStory.tsx, components/StoryPoC/VideoScrollStory.tsx, components/Storyblok/SbStory.tsx, components/Typography/Text.tsx, components/Typography/typography.styles.ts
- POC build for Kerri's horizontal brochure idea
- new CTA style
- Retro
1. https://deploy-preview-118--giving-campaign.netlify.app/stories/poc-solve-for-now
2. Make sure you click through all the pages in each "Chapter" (3 pages in the first one, 4 pages in the 2nd one)
- JIRA ticket(s) - GIVCAMP-188
=> GIVCAMP-188 | Horizontal brochure poc; new CTA style

components/ScrollyTelling/ScrollyDataViz.tsx, components/Storyblok/SbStory.tsx
- A quick POC for doing low budget "data viz"
- Retro
1. GO to https://deploy-preview-119--giving-campaign.netlify.app/stories/immersive-featured-story-test
2. Scroll to the bottom section below the animated Pusheen
3. Check that you see the first barchart
4. And when you scroll down to heading 2, the bar chart bars animate plus the numbers change
- JIRA ticket(s) - GIVCAMP-194
=> GIVCAMP-194 | Low budget data viz poc

components/Homepage/Changemaker.tsx, components/Homepage/IdealFellow.tsx, components/Storyblok/SbHomepage.tsx
- Ideal Fellow section with parallax effect
- Retro
1. Go to the homepage
https://deploy-preview-121--giving-campaign.netlify.app/
and check out the IDEAL fellow Hector section. Test out hocus effect
- JIRA ticket(s) - GIVCAMP-198
=> GIVCAMP-198 | homepage Ideal fellow section with parallax explore

components/Homepage/HomepageSplitHero.tsx, components/Storyblok/SbHomepage.tsx, components/Typography/typography.styles.ts, tailwind/plugins/components/gc-typography.js
- New homepage hero, and animation
- Retro
1. Go to the preview and look at the hero
https://deploy-preview-122--giving-campaign.netlify.app/
- JIRA ticket(s) - GIVCAMP-199
=> GIVCAMP-199 | New homepage hero

components/BlurryPoster/BlurryPoster.styles.tsx, components/BlurryPoster/BlurryPoster.tsx, components/Hero/StoryHero.tsx, components/Hero/StoryHeroMvp.styles.ts, components/Hero/StoryHeroMvp.tsx, components/Hero/index.ts, components/Masthead/Masthead.tsx, components/Storyblok/SbBlurryPoster.tsx, components/Storyblok/SbStoryMvp.tsx, components/StoryblokProvider.tsx
- Story hero variants
- Retro
Look at all the below variants including responsive:
1. Dark theme with background image, serif small headline, vertical layout
https://deploy-preview-131--giving-campaign.netlify.app/stories/overcoming-racial-disparities-in-california-neonatal-intensive-care-units
3. Dark theme with background image, custom mixed font long headline, vertical layout
https://deploy-preview-131--giving-campaign.netlify.app/stories/test-story-hero-mixed-font-vertical
4. Light theme with background image, serif larger headline, vertical layout
https://deploy-preview-131--giving-campaign.netlify.app/stories/test-story-hero-white-background-vertical
5. Dark theme with background image, custom mixed font long headline, horizontal layout …
=> GIVCAMP-221 | New Story Hero

components/Cta/Cta.styles.ts, components/Hero/StoryHero.tsx, components/Hero/StoryHeroMvp.tsx, components/RichText.tsx, components/Sidebar/SidebarCard.styles.ts, components/Sidebar/SidebarCard.tsx, components/Sidebar/index.ts, components/Storyblok/SbCardWysiwyg.tsx, components/Storyblok/SbSidebarCard.tsx, components/Storyblok/SbStoryMvp/SbAboveContent.tsx, components/Storyblok/SbStoryMvp/SbStoryMvp.tsx, components/Storyblok/SbStoryMvp/index.ts, components/Storyblok/SbWysiwyg.tsx, components/StoryblokProvider.tsx, components/VerticalCard/VerticalCard.tsx, utilities/colorPalettePlugin.ts, utilities/datasource.ts
- Sidebar Card component
- "Above content" region for Story page type
- Retro
Look at these sidebar card variants
1. https://deploy-preview-135--giving-campaign.netlify.app/stories/test-story-hero-mixed-font-horizontal
2. https://deploy-preview-135--giving-campaign.netlify.app/stories/overcoming-racial-disparities-in-california-neonatal-intensive-care-units
- JIRA ticket(s) - GIVCAMP-222
=> GIVCAMP-222 | Story above content region; sidebar card

components/Quote/Quote.styles.ts, components/Quote/Quote.tsx, components/Quote/index.ts, components/Sidebar/SidebarCard.styles.ts, components/Sidebar/SidebarCard.tsx, components/Storyblok/SbQuote.tsx, components/Storyblok/SbSection.tsx, components/Storyblok/SbSidebarCard.tsx, components/Storyblok/SbStoryMvp/SbAboveContent.tsx, components/Storyblok/SbStoryMvp/SbStoryMvp.tsx, components/StoryblokProvider.tsx, utilities/datasource.ts
- Quote component (different variants and options)
- Retro
Go to this preview
1. https://deploy-preview-138--giving-campaign.netlify.app/stories/test-story-hero-mixed-font-horizontal
2. Scroll down and see the different variants
3. Check the responsive behavior
- JIRA ticket(s) - GIVCAMP-98
=> GIVCAMP-98 | Quote component

components/Banner/Banner.styles.ts, components/Banner/Banner.tsx, components/Storyblok/SbBanner.tsx
- Ankle banner update for MVP rebrand
- Retro
1. Scroll below the story content to see the ankle banner
https://deploy-preview-139--giving-campaign.netlify.app/stories/test-story-hero-mixed-font-horizontal
2. Check that the body font is normal weight, and that the image has no curved corners
- JIRA ticket(s) - GIVCAMP-236
=> GIVCAMP-236 | Ankle banner update for MVP

app/layout.tsx, components/Bookshelf/BookAlt.tsx, components/GlobalFooter/GlobalFooter.tsx, components/Masthead/Masthead.tsx, components/StoryPoC/ProgressStory.tsx, components/Storyblok/SbSplitPoster.tsx, components/Typography/typography.styles.ts, tailwind/plugins/theme/gc-fontFamily.js
- Misc maintenance stuff that I wanted to do
- This is only the first batch
- Global footer update to match decanter 6 - use vanity url for non-discrimination link, add rel="nofollow" to all external links
- Get rid of the remaining any[] types
- get rid of the mono font in PoCs that clients decide not to use for MVP
- Move skiplink to within the header landmark in the masthead
- Retro
1. Look at the code
- JIRA ticket(s) - GIVCAMP-225
=> GIVCAMP-225 | Maintenance

components/Container/Container.types.ts, components/EmbedMedia/EmbedMedia.styles.ts, components/EmbedMedia/EmbedMedia.tsx, components/EmbedMedia/index.ts, components/LocalFooter/LocalFooter.tsx, components/Storyblok/SbEmbedMedia.tsx, components/Storyblok/SbStoryMvp/SbStoryMvp.tsx, components/StoryblokProvider.tsx, components/Typography/typography.styles.ts, package-lock.json, package.json, tailwind/plugins/components/gc-typography.js, utilities/datasource.ts
- Media embed (Vimeo, Youtube etc)
- Retro
Look at these video embeds in the following:
1. https://deploy-preview-143--giving-campaign.netlify.app/stories/test-story-hero-mixed-font-vertical
2. https://deploy-preview-143--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose
- JIRA ticket(s) - GIVCAMP-246
=> GIVCAMP-246 | Embed Media component

app/layout.tsx, components/Homepage/TogetherSection.tsx, components/LocalFooter/LocalFooter.tsx, components/LocalFooter/LocalFooterMvp.styles.tsx, components/LocalFooter/LocalFooterMvp.tsx, components/LocalFooter/index.ts, utilities/externalLinks.ts
- New local footer
- Retro
This is the Figma mock
1. https://deploy-preview-156--giving-campaign.netlify.app/
2. Scroll to the bottom to see the new local footer
3. Check all responsive
- JIRA ticket(s) - GIVCAMP-165
=> GIVCAMP-165 | New local footer

components/Storyblok/SbTypeform.tsx
- Plays around with the TypeForm embed and the Section component
- Re: https://stanfordwebservices.slack.com/archives/C03R765SAJC/p1701205448577029
- When you can
-  Low
1. Check out the [preview build page ](https://deploy-preview-164--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose)
2. Scroll down to the bottom
3. Resize for mobile and review
=> NoJira: Remove heading and adjust padding on the Typeform

components/BlurryPoster/BlurryPoster.tsx, components/FeaturedStories/FeatureMasonry.tsx, components/ImageOverlay.tsx, components/Quote/Quote.styles.ts, components/Quote/Quote.tsx, components/RichText.tsx, components/Storyblok/SbFeatureMasonry.tsx
- Masonry Grid update
- other misc updates
- Retro
1. Go to https://deploy-preview-167--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose
2. Look at this media grid and check all breakpoints
3. Check that it more or less matches the Figma. NOTE: Vimeo video has to be 16:9 since that is what they uploaded so I adjust the aspect ratio of the bottom row items.
https://www.figma.com/file/W79cNz01bKsUz9unfnSzB7/Interactive-Story-Ideas-(Aug-2023)?type=design&node-id=1803%3A20635&mode=dev&t=fYlOC5liEUZBgCQt-1
- JIRA ticket(s) - GIVCAMP-245
=> GIVCAMP-245 | Featured story masonry media grid and misc updates

components/RichText.tsx, components/Sidebar/SidebarCard.styles.ts, components/Sidebar/SidebarCard.tsx, components/Storyblok/SbCardWysiwyg.tsx, components/Storyblok/SbQuote.tsx, components/Typography/SrOnlyText.tsx, utilities/colorPalettePlugin.ts, utilities/datasource.ts
- Misc updates for sidebar card so we can do certain layouts in the featured stories
- Retro
1. https://deploy-preview-169--giving-campaign.netlify.app/stories/it-s-like-herding-atoms
2. scroll down to look at this card
3. Confirm that light text with black translucent background with backdrop blur is possible
- JIRA ticket(s) - GIVCAMP-263
=> GIVCAMP-263 | Update sidebar card

app/(storyblok)/[[...slug]]/page.tsx
- See if this helps with caching.
=> Set slug route segment to revalidate 0

components/BlurryPoster/BlurryPoster.tsx, components/Hero/BasicHeroMvp.tsx, components/Hero/index.ts, components/Homepage/HomepageSplitHero.tsx, components/Homepage/TogetherSection.tsx, components/LocalFooter/LocalFooterMvp.tsx, components/Scrollytelling/Scrollytelling.styles.ts, components/Storyblok/SbBasicPage.tsx, tailwind/plugins/base/gc-base.js, utilities/externalLinks.ts, utilities/routes.ts
- A generic basic page hero for MVP
- Before the break?
1. Check that clicking on below link goes to 404 page
https://deploy-preview-181--giving-campaign.netlify.app/monkey-business
2. Check newsletter page layout
https://deploy-preview-181--giving-campaign.netlify.app/newsletter/signup
3. Look at things called out and code
- JIRA ticket(s) - GIVCAMP-270
=> GIVCAMP-270 | Basic page hero

utilities/routes.ts
=> Nojira | Changing slug of sign up page because sign up is 2 words

next.config.js
=> Change redirect to target RSC.

app/(editor)/editor/page.tsx
- Passes slug to editor storyblok component to enable Social Sharing bar 
- End of sprint
- Low
1. Load up [a page with the preview build](https://app.storyblok.com/#/me/spaces/1005200/stories/0/0/1622839?env=PR+194) in storyblok
3. See social sharing
=> GIVCAMP-274: Pass slug to StoryblokStory component.

app/layout.tsx, components/GAProvider.tsx, next.config.js
- Adds GTM container on branch and production deploys
- End of sprint
- Normal
1. Open up the preview build and inspect the HTML `<head>` 
2. You should not see the GTM container
3. Pull the code down to your local
4. Add `CONTEXT="production"` to your environment variables
5. Run `npm run dev`
6. Load up the home page on local 
7. Validate that the GTM container is added to the head.
=> GIVCAMP-228: Add GTM Container.

app/(storyblok)/loading.tsx, app/loading.tsx, components/BlurryPoster/BlurryPoster.styles.tsx, components/BlurryPoster/BlurryPoster.tsx, components/Homepage/HomepageSplitHero.tsx, components/TexturedBar/TexturedBar.tsx
=> GIVCAMP-278 | Test image using picture with art direction

components/Homepage/Changemaker.tsx, components/Homepage/HomepageSplitHero.tsx
=> Nojira | Homepage copy update

components/TypeForm/PopUp.tsx, package-lock.json, package.json
- Update netlify plugin vault variables which uses node 20
- Soon
- 3
1. Look at the preview and that it's still working
2. Look at code
=> NOJIRA | Update netlify plugin vault variables which uses node 20

app/(editor)/editor/page.tsx
- Adds a new environment variable for configuring the visual editor token validation
=> Bugfix: Add editor token.

app/(editor)/editor/page.tsx
- Bugfix: Add preview token for the editor path
- Soon
- Demos are always smoke and mirrors
=> Release: v1.0.2

app/(editor)/editor/page.tsx
=> Bugfix: Add editor token... Everywhere

utilities/datasource.ts
=> Fix | datasource heroOverlay black-10 typo

components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.styles.ts, components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.tsx, components/Storyblok/SbHomepageThemeSection/index.ts, components/StoryblokProvider.tsx, tailwind.config.ts, tailwind/plugins/components/gc-text-shadow.js, utilities/datasource.ts
- New homepage story/theme sections
- This PR is just for the wrapper. Additional work will have to be done for everything to look like the mock here
https://www.figma.com/file/lgVl7UtcrFAejjH9eTfF8f/Momentum-Design-System?type=design&node-id=10576%3A16947&mode=dev
- Retro
1. Pull this down locally and do `npm run dev`
2. See the test/home-new-test page on Storyblok (not published)
- JIRA ticket(s) - GIVCAMP-285
=> GIVCAMP-285 | Homepage theme story section

components/StoryCard/StoryCard.styles.tsx, components/StoryCard/StoryCard.tsx, components/Storyblok/SbStoryCard.tsx
- Horizontal variant for the story cards
- Retro
1. Pull down this branch `npm run dev`, and locally go to test/home-new-test on Storyblok
2. Look at the page and the code
- JIRA ticket(s) - GIVCAMP-288
=> GIVCAMP-288 | story card horizontal variant

components/StoryCard/StoryCard.styles.tsx, components/StoryCard/StoryCard.tsx, components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.styles.ts, components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.tsx, components/Storyblok/SbHomepageThemeSection/index.ts, components/Storyblok/SbStoryCard.tsx, components/StoryblokProvider.tsx, tailwind.config.ts, tailwind/plugins/components/gc-text-shadow.js, utilities/datasource.ts
- #226 
- #227 
- #228 
- #229 
- EOD Friday
1. Look at the code diff.
2. Check the preview that it doesn't break anything. You won't see anything new yet because new content on the homepage isn't published yet.
=> Release v1.1.0

components/MomentPoster/MomentPoster.styles.ts, components/MomentPoster/MomentPoster.tsx, components/MomentPoster/index.ts, components/StoryImage/StoryImage.tsx, components/Storyblok/SbMomentPoster.tsx, components/StoryblokProvider.tsx, utilities/datasource.ts
- Moment Poster component
- Retro
- 5
1. Pull down locally and go to test/test-initiative-template
2. Scroll down to play with the 2 moment posters and all the options
- JIRA ticket(s) - GIVCAMP-293
=> GIVCAMP-293 | Moment poster

app/robots.ts
=> Update robots to use different URL for sitemap path

components/Container/Container.styles.ts, components/EmbedMedia/EmbedMedia.styles.ts, components/Hero/StoryHeroMvp.styles.ts, components/Hero/StoryHeroMvp.tsx, components/Parallax/Parallax.tsx, components/Parallax/index.ts, components/Storyblok/SbSection/SbSection.styles.ts, components/Storyblok/SbVerticalPoster.tsx, components/Storyblok/Storyblok.types.ts, components/StoryblokProvider.tsx, components/VerticalPoster/VerticalPoster.styles.ts, components/VerticalPoster/VerticalPoster.tsx, package-lock.json, package.json
- Vertical Poster component with parallax feature
- Update framer motion and usehook-ts
- Misc minor component updates
- Retro
- 6
1. Go to storyblok test/test-stories/yvonne-test-arts-feature and pick PR 253 from the visual editor
2. Scroll down to see the vertical posters (first 3 has parallax, last one is the old design with regular static images)
3. Play with the options
4. Check all breakpoints
- JIRA ticket(s) - GIVCAMP-313
=> GIVCAMP-313 | Vertical poster component with parallax

public/google83a00cb6501cf923.html
- Google console verification file
=> NoJira: Verify file for google console.

public/google83a00cb6501cf923.html
- Add Google console verification file
- Retro
Console owner is sws developers gmail account.
=> Release: v1.4.2

components/Row/Row.styles.ts, components/Row/Row.tsx, components/Row/Row.types.ts, components/Row/index.ts, components/Sidebar/SidebarCard.styles.ts, components/Sidebar/SidebarCard.tsx, components/Storyblok/SbRow.tsx, components/Storyblok/SbSidebarCard.tsx, components/Storyblok/SbSpacer.tsx, components/Storyblok/SbText.tsx, components/StoryblokProvider.tsx, components/TextCard/TextCard.styles.ts
- Row and Spacer component
- Misc updates (see things called out below)
- Retro
- 3
1. Go to storyblok test/row-test
2. Pick PR 269 from the visual editor URL
3. Look at all the examples and the options available
- JIRA ticket(s) - GIVCAMP-298
=> GIVCAMP-298 | Row component with spacers; misc updates

components/LocalFooter/LocalFooter.tsx, components/LocalFooter/LocalFooterMvp.tsx, utilities/routes.ts
- Update local footer links
- Retro
- 8
1. Look at the preview and check that the Initiative and Game Changers links are working
- JIRA ticket(s) - GIVCAMP-338
=> GIVCAMP-338 | Update local footer links

app/layout.tsx, components/Heap.tsx
- Adds Heap Analytics
- EOW
- Hoping to have this up and in production by EOD on the 1st
1. Review code
2. Check out a local branch
3. Set your `.env` file `CONTEXT` to `production`
4. Run `npm run dev`
5. Load up the home page or other pages
6. Review console log and network tab to see heap analytics loading
7. Change `CONTEXT` to anything else and repeat steps
8. Ensure script doesn't load
=> GIVCAMP-344: Add Heap Analytics

components/LocalFooter/LocalFooterMvp.tsx, utilities/routes.ts
- Change link in footer from "Gamer changers" to "Changemakers"
- Retro
- 8
1. Look at the preview and the local footer link
=> Nojira | Back to changemakers link in footer

components/BlurryPoster/BlurryPoster.styles.tsx, components/BlurryPoster/BlurryPoster.tsx, components/Hero/StoryHeroMvp.tsx, components/Hero/StoryHeroStacked.styles.ts, components/Hero/StoryHeroStacked.tsx, components/Typography/Text.tsx
- Add optional byline and published date to story heroes (all variants)
- Retro
- 6
1. Review these story heroes
https://deploy-preview-281--giving-campaign.netlify.app/stories/education-for-a-life-of-purpose
https://deploy-preview-281--giving-campaign.netlify.app/stories/the-second-envelope
https://deploy-preview-281--giving-campaign.netlify.app/stories/cartographer-of-cancer
https://deploy-preview-281--giving-campaign.netlify.app/stories/experiments-without-experimenting (this one doesn't have a byline)
2. Quick responsive check
- JIRA ticket(s) - GIVCAMP-348
=> GIVCAMP-348 | Add optional byline and published date to story heroes

components/Cta/Cta.styles.ts, tailwind/plugins/base/gc-base.js
- Use Campaign black as base HTML body text color
- Retro
- 2
1. I've asked the client to QA this and it has passed so we're good.
=> Nojira | Use Campaign black for body text color in TW base

components/Homepage/TogetherSection.tsx
- Homepage update game changer wording to changemaker
- Retro
- 4
1. look at code is enough
=> Nojira | Homepage update game changer wording to changemaker

components/ChangemakerCard/ChangemakerCard.styles.ts
=> no hyphen between TW class whitespace (#296)

components/BlurryPoster/BlurryPoster.styles.tsx, components/BlurryPoster/BlurryPoster.tsx, components/Cta/Cta.styles.ts, components/Hero/StoryHeroMvp.tsx, components/Hero/StoryHeroStacked.styles.ts, components/Hero/StoryHeroStacked.tsx, components/StoryCard/StoryCard.styles.tsx, components/StoryCard/StoryCard.tsx, components/Storyblok/SbStoryMvp/SbStoryMvp.tsx, utilities/taxonomyMaps.ts
- Add tags to the 2 story hero variants
- Retro
- 5
1. Go to https://deploy-preview-304--giving-campaign.netlify.app/stories/capturing-success
2. Check that the tags in the hero gets rendered
3. Go to https://deploy-preview-304--giving-campaign.netlify.app/stories/cartographer-of-cancer
4. Check that tags are rendered in the hero and are center aligned
- JIRA ticket(s) - GIVCAMP-360
=> GIVCAMP-360 | Add tags to story heroes (default and stacked heroes)

components/GAProvider.tsx, package-lock.json, package.json
- Swaps out Next Script for Next Third Parties Library
- Whenever
- Low
1. Review [preview build ](https://deploy-preview-315--giving-campaign.netlify.app/)and ensure GTM is not added
2. Pull down the code to your local
3. Set your `.env` file with the `CONTEXT="branch-deploy"`
4. Fire up a dev instance
5. Review to ensure GTM is added
=> GIVCAMP-324: Switch to next third parties for GTM

components/Homepage/Changemaker.tsx
=> Nojira | Hide changemaker section on homepage if no changemaker cards added

components/Storyblok/SbSection/SbSection.tsx
=> Nojira | Making the subhead lighter for accessibility

components/LocalFooter/LocalFooterMvp.tsx, utilities/routes.ts
- Update local footer contact us link
- Retro
- 5
- JIRA ticket(s) - GIVCAMP-367
=> GIVCAMP-367 | Update contact us link to internal link in local footer

utilities/data/getStoryData.ts, utilities/data/getStoryList.ts
- Do env check so we have the token needed for production.
3. Verify...
- Other PRs
=> Check for active env in getStoryData

components/Hero/StoryListHero.styles.ts, components/Hero/StoryListHero.tsx
- Add animation to H1 on story filter pages so route change is more obvious
- Retro
- 2
1. 
- JIRA ticket(s) - GIVCAMP-370
=> GIVCAMP-370 | Add animation to story filter page h1

components/LocalFooter/LocalFooterMvp.tsx
- Add "Stories" to local footer and have the 4 links in order that's like in Main Nav
- Retro
- 6
1. Looking at code is probably enough
- JIRA ticket(s) - GIVCAMP-374
=> GIVCAMP-374 | Add Stories to local footer and reorder links

utilities/taxonomyMaps.ts
- Adding a new theme
- NOTE: New filter pages have been created in Storyblok, but they won't be published until the week of Sep 9. Also, they will not use this new tag and the "Stanford Public Humanities" one until these 2 new pages are published.
- Retro
- 5
2. Do a quick check of the homepage story card - they should not be affected in any ways.
- JIRA ticket(s) - GIVCAMP-379
=> GIVCAMP-379 | Adding a new theme

README.md, docs/environment-variables.md, netlify.toml, netlify/functions/storyblok-background.mts, package-lock.json, package.json
- Creates a webhook to validate that the change is 'in' or affects the current site
- Sister PR to https://github.com/SU-SWS/ood-stanford-tour/pull/12
- End of sprint
- Normal
1. Make a change in Storyblok to a story (publish, unpublish, move, delete)
2. Review webhook logs for success payload
3. Review Slack channel #sws-netlify-builds for logs
4. Review background function logs
5. Review netlify build logs to ensure a build did or did not build (If change in tour folder, asset, or datasource it should be building)
6. Make a change in the tour folder content (story)
7. Ensure no builds on momentum
8. Make a change to an asset and a datasource
9. Ensure a build is triggered on both sites
- DS-955: Webhook
- [Storyblok Space](https://app.storyblok.com/#/me/spaces/1021829/stories/0/0/index/0 …
=> DS-917: Deploy webhook

app/(editor)/editor/page.tsx
- Removes signature check for preview editor path
- Retro
=> Remove signature check due to Storyblok silliness.

.adr-dir, README.md, app/(editor)/editor/page.tsx, app/(storyblok)/[[...slug]]/not-found.tsx, app/(storyblok)/[[...slug]]/page.tsx, app/not-found.tsx, app/sitemap.ts, components/Cta/CtaLink.tsx, components/Cta/CtaNextLink.tsx, components/Storyblok/SbStoryFilterPage/SbStoryFilterPage.tsx, components/Storyblok/SbStoryListNav/SbStoryListNav.tsx, docs/decisions/0002-split-content-directories-and-slug-handling.md, docs/decisions/0003-active-environment-is-the-context-environment-variable.md, docs/environment-variables.md, netlify.toml, netlify/functions/storyblok-background.mts, next.config.js, package-lock.json, package.json, utilities/data/getStoryData.ts, utilities/data/getStoryList.ts, utilities/getActiveEnv.ts, utilities/getPageMetadata.ts, utilities/getSlugPrefix.ts, utilities/sbStripSlugUrl.ts
- Retro
* DS-916: Split paths and Slug Prefix. (#350) 
* DS-917: Deploy webhook (#351) 
* Remove editor signature validation check in favor of straight key check
=> Release: v3.0.0

netlify/functions/storyblok-background.mts
- Always use preview token so we don't get a 401 when trying to find out about content
- Retro
=> Release: v3.0.1

app/(storyblok)/[[...slug]]/not-found.tsx, app/(storyblok)/[[...slug]]/page.tsx, app/not-found.tsx, app/sitemap.ts, utilities/data/getStoryData.ts, utilities/data/getStoryList.ts
- Hotfix, API throttling
- ASAP
- 9000
=> HOTFIX: API Throttling.

app/(storyblok)/[[...slug]]/not-found.tsx, app/(storyblok)/[[...slug]]/page.tsx, app/not-found.tsx, app/sitemap.ts, utilities/data/getStoryData.ts, utilities/data/getStoryList.ts
- Hotfix, Storyblok API throttling
=> Release: v3.0.2

components/AnnotatedImage/AnnotatedImage.tsx, components/Banner/Banner.tsx, components/Storyblok/SbAnnotatedImage.tsx
- Push up last commit that I forgot for the annotated image 🤦🏼‍♀️ 
- Better keys for hotspot list items
- Honor "priority loading" option for annotated image
- Lazy load ankle banner image
- retro
- 4
1. Look at code probably enough
- JIRA ticket(s) - DS-850
=> DS-850 | A few fixups for annotated image

app/(editor)/editor/page.tsx, utilities/data/getStoryData.ts
- Force a preview editor token in editor through SB Params
- Soonish
- Normal
1. Review code
2. Go to storyblok and try to load a few pages in the Preview Build URL to see if you get WPOD
=> NoJira: Force token through sbParams.

app/(editor)/editor/page.tsx, app/(storyblok)/[[...slug]]/page.tsx, next.config.mjs, utilities/data/getStoryData.ts, utilities/data/getStoryblokRedirects.mjs
- DS-918: Storyblok Redirects. (#357)
- NoJira: Force token through sbParams. (#360)
- Retro
=> Release: v3.2.0

utilities/data/getStoryblokRedirects.mjs
- Allows the redirects configured in storyblok to contain a wildcard
- Whenver
- Low
1. Add a wildcard redirect in SB. eg (/test/*)
2. Ensure it catches all `/test/{xyz}` paths
=> Support wildcards in redirects.

utilities/externalLinks.ts
- Ensure all links go to dev netlify sites
- End of the sprint
- Low
1. Review code
2. Comment on anywhere I may have forgotten
3. I am going to look into the CMS separately
=> DS-1060: Ensure all links go to dev Netlify sites.

app/(editor)/editor/layout.tsx, components/Sa11y/Sa11y.tsx, components/Sa11yInit/Sa11yInit.tsx, components/Sa11yInit/index.ts, package-lock.json, package.json, tsconfig.json, types/sa11y.d.ts
- Add Sa11y to Storyblok editing
- Soon
- 5
1. Go to Momentum Storyblok
2. Open up any page in the Momentum directory
3. Select PR 383 from the visual editor URL
4. Check that it has the normal Sa11y functionality and there are no errors
- JIRA ticket(s) - DS-1101
=> DS-1101 | Add Sa11y

components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.styles.ts, components/Storyblok/SbHomepageThemeSection/SbHomepageThemeSection.tsx, components/Storyblok/SbSection/SbSection.styles.ts
- Adjust Section heading sizes and add options to the homepage sections
- Retro
Note: Approved by client already
- 4
1. Look at the homepage and the code
- JIRA ticket(s) - DS-1143
=> DS-1143 | Adjust Section heading sizes

components/Animate/AnimateInView.tsx, components/LazyMotionProvider.tsx, components/Storyblok/SbTabGroup.tsx, components/Storyblok/Storyblok.types.ts, components/StoryblokProvider.tsx, components/Tabs/Tabs.styles.ts, components/Tabs/Tabs.tsx, components/Tabs/index.ts, hooks/useKeyboard.ts, utilities/slugify.ts
- Add Tabs/Agenda component to Momentum
- Already in Tour - this PR brings this code over to Momentum side with font change
- https://github.com/SU-SWS/ood-stanford-tour/pull/43, https://github.com/SU-SWS/ood-stanford-tour/pull/51
- Retro
- 5
1. Go to Momentum/Test/Yvonne Test Agenda. 
2. Select PR 391 from the visual editor
- JIRA ticket(s) - DS-1176
=> DS-1176 | Add Tabs/Agenda to Momentum

package-lock.json, package.json
- Update Next.js to v14.2.3 (latest one for v14)
- Update @netlify/plugin-nextjs to latest (@sherakama we previously agree on manually installing a known version instead of relying on netlify to choose. I'm open to changing my mind however)
- Update some other packages
- Retro
- 3
1. Look at the preview and check that things are working as before
2. Look at what's been updated
=> Update Next.js to lastest v14 (v14.2.23) and other packages

components/EmbedMedia/EmbedMedia.tsx, components/FeaturedStories/FeatureMasonry.tsx, components/Hero/StoryHeroMvp.styles.ts, components/Hero/StoryHeroMvp.tsx, components/Media/MediaWrapper.styles.ts, components/Media/index.ts, components/Scrollytelling/Scrollytelling.tsx, components/SocialSharing/SocialButton.tsx, components/SocialSharing/SocialSharing.styles.ts, components/SocialSharing/SocialSharing.tsx, components/StoryImage/StoryImage.styles.ts, components/Storyblok/SbAnnotatedImage.tsx, components/Storyblok/SbEmbedMedia.tsx, components/Storyblok/SbFeatureMasonry.tsx, components/Storyblok/SbScrollytelling.tsx, components/Storyblok/SbSection/SbSection.styles.ts, components/Storyblok/SbStoryImage.tsx, components/Storyblok/SbStoryMvp/SbStoryMvp.tsx, components/Storyblok/SbVideo.tsx, components/Typography/typography.styles.ts, package-lock.json, package.json
- Add option for Story page to have dark background
- Retro
- 6
1. Review previews posted on https://stanfordwebservices.slack.com/archives/C03R765SAJC/p1741631248144629
2. Check existing stories and see that they're not affected
- JIRA ticket(s) - DS-1144
=> DS-1144 | Dark Story option
